// OSRS WORDLE ITEM HINTS
// Format: { itemName, emojiHint (5 emojis), wordHint (5-letter word) }
// Categories: Metals & Ores, Melee Weapons, Ranged, Magic, Armour, Food, Potions,
//             Skilling, Jewellery, Runes, Quest Items, Monsters, Misc

export const WORD_LIST = [
	// ============================================================
	// ORES & BARS
	// ============================================================
	{ itemName: 'Copper ore', emojiHint: '🟠⛏️🪨🔥🔩', wordHint: 'mine' },
	{ itemName: 'Tin ore', emojiHint: '⚪⛏️🪨🔩🏭', wordHint: 'smelt' },
	{ itemName: 'Iron ore', emojiHint: '🟤⛏️🪨🔩⚙️', wordHint: 'forge' },
	{ itemName: 'Coal', emojiHint: '⚫⛏️🪨🔥🏭', wordHint: 'black' },
	{ itemName: 'Silver ore', emojiHint: '🪙⛏️🪨✨💍', wordHint: 'shine' },
	{ itemName: 'Gold ore', emojiHint: '🟡⛏️🪨✨💍', wordHint: 'bling' },
	{ itemName: 'Mithril ore', emojiHint: '🔵⛏️🪨🔩💎', wordHint: 'bluerock' },
	{ itemName: 'Adamantite ore', emojiHint: '🟢⛏️🪨🔩💎', wordHint: 'green' },
	{ itemName: 'Runite ore', emojiHint: '🩵⛏️🪨💎🏆', wordHint: 'rare' },
	{ itemName: 'Amethyst', emojiHint: '💜⛏️🪨💎🏹', wordHint: 'arrow' },
	{ itemName: 'Lovakite ore', emojiHint: '🟤⛏️🏰💎🔩', wordHint: 'kourend' },
	{ itemName: 'Volcanic ash', emojiHint: '🌋⛏️💨⚫🏝️', wordHint: 'ashen' },
	{ itemName: 'Drakolith', emojiHint: '🐉⛏️🪨💎🔩', wordHint: 'drake' },
	{ itemName: 'Orichalcite ore', emojiHint: '🟠⛏️💎🔩⚙️', wordHint: 'alloy' },
	{ itemName: 'Bronze bar', emojiHint: '🟫🔥⚒️🔩🏭', wordHint: 'alloy' },
	{ itemName: 'Iron bar', emojiHint: '⚫🔥⚒️🔩🏭', wordHint: 'forge' },
	{ itemName: 'Steel bar', emojiHint: '⚙️🔥⚒️🔩🏭', wordHint: 'smith' },
	{ itemName: 'Silver bar', emojiHint: '🪙🔥⚒️✨🏭', wordHint: 'craft' },
	{ itemName: 'Gold bar', emojiHint: '🟡🔥⚒️✨🏭', wordHint: 'craft' },
	{ itemName: 'Mithril bar', emojiHint: '🔵🔥⚒️💎🏭', wordHint: 'smith' },
	{ itemName: 'Adamant bar', emojiHint: '🟢🔥⚒️💎🏭', wordHint: 'smith' },
	{ itemName: 'Rune bar', emojiHint: '🩵🔥⚒️💎🏭', wordHint: 'smelt' },
	{ itemName: 'Lovakite bar', emojiHint: '🟤🔥⚒️🏰🏭', wordHint: 'kourend' },
	{ itemName: 'Necronium bar', emojiHint: '💀🔥⚒️🔩🏭', wordHint: 'death' },

	// ============================================================
	// LOGS & WOODCUTTING
	// ============================================================
	{ itemName: 'Logs', emojiHint: '🪵🌲🪓🔥🏕️', wordHint: 'chop' },
	{ itemName: 'Oak logs', emojiHint: '🌳🪓🪵🔥🏚️', wordHint: 'oaken' },
	{ itemName: 'Willow logs', emojiHint: '🌿🪓🪵💧🔥', wordHint: 'droop' },
	{ itemName: 'Teak logs', emojiHint: '🌴🪓🪵🏠🔥', wordHint: 'build' },
	{ itemName: 'Maple logs', emojiHint: '🍁🪓🪵🔥🍬', wordHint: 'syrup' },
	{ itemName: 'Mahogany logs', emojiHint: '🌴🪓🪵🏛️🔥', wordHint: 'build' },
	{ itemName: 'Yew logs', emojiHint: '🏹🌲🪓🪵🔥', wordHint: 'arrow' },
	{ itemName: 'Magic logs', emojiHint: '✨🌲🪓🪵🔮', wordHint: 'spell' },
	{ itemName: 'Redwood logs', emojiHint: '🌲🪓🪵🔴🏆', wordHint: 'giant' },
	{ itemName: 'Blisterwood logs', emojiHint: '🧛🪵🪓🌲✨', wordHint: 'vampyr' },
	{ itemName: 'Bark', emojiHint: '🌲🪵🔪🌿🐕', wordHint: 'outer' },
	{ itemName: 'Blessed axe', emojiHint: '✝️🪓⚔️🌲✨', wordHint: 'holy' },

	// ============================================================
	// FISH (RAW)
	// ============================================================
	{ itemName: 'Raw shrimps', emojiHint: '🦐🌊🎣🪣🟡', wordHint: 'small' },
	{ itemName: 'Raw sardine', emojiHint: '🐟🌊🪝🟡🎣', wordHint: 'bait' },
	{ itemName: 'Raw herring', emojiHint: '🐟🌊🪝🔴🎣', wordHint: 'bait' },
	{ itemName: 'Raw anchovies', emojiHint: '🐟🌊🕸️🧂🎣', wordHint: 'salty' },
	{ itemName: 'Raw mackerel', emojiHint: '🐟🌊🕸️🔵🎣', wordHint: 'bignet' },
	{ itemName: 'Raw trout', emojiHint: '🐟🌊🪰🏞️🎣', wordHint: 'river' },
	{ itemName: 'Raw cod', emojiHint: '🐟🌊🕸️🇬🇧🎣', wordHint: 'bignet' },
	{ itemName: 'Raw pike', emojiHint: '🐟🌊🪝🦷🎣', wordHint: 'bait' },
	{ itemName: 'Raw salmon', emojiHint: '🐟🌊🪰🏔️🎣', wordHint: 'flies' },
	{ itemName: 'Raw tuna', emojiHint: '🐟🌊🔱🎣💪', wordHint: 'harpoon' },
	{ itemName: 'Raw lobster', emojiHint: '🦞🌊🪤🎣🔴', wordHint: 'pot' },
	{ itemName: 'Raw bass', emojiHint: '🐟🌊🕸️🔵🎣', wordHint: 'bignet' },
	{ itemName: 'Raw swordfish', emojiHint: '🗡️🐟🌊🔱🎣', wordHint: 'harpoon' },
	{ itemName: 'Raw monkfish', emojiHint: '🐟🕸️🏝️🏆🎣', wordHint: 'quest' },
	{ itemName: 'Raw karambwan', emojiHint: '🐙🌴🏝️🎣⚡', wordHint: 'vessel' },
	{ itemName: 'Raw shark', emojiHint: '🦈🌊🔱🎣😱', wordHint: 'harpoon' },
	{ itemName: 'Raw sea turtle', emojiHint: '🐢🌊🎣🏝️🕸️', wordHint: 'trawl' },
	{ itemName: 'Raw manta ray', emojiHint: '🌊🪁🎣🕸️🐠', wordHint: 'trawl' },
	{ itemName: 'Raw anglerfish', emojiHint: '💡🐟🌊🎣😈', wordHint: 'worms' },
	{ itemName: 'Raw dark crab', emojiHint: '🦀🌑🌊🎣⚠️', wordHint: 'wilds' },
	{ itemName: 'Raw cave eel', emojiHint: '🐍🕳️🌊🎣🏔️', wordHint: 'slime' },
	{ itemName: 'Raw lava eel', emojiHint: '🌋🐍🎣🔥🌊', wordHint: 'lava' },
	{ itemName: 'Raw rainbow fish', emojiHint: '🌈🐟🌊🪰🎣', wordHint: 'flies' },
	{ itemName: 'Infernal eel', emojiHint: '🌋🐍🔥🗺️⚡', wordHint: 'tokkul' },
	{ itemName: 'Minnow', emojiHint: '🐟🌊🦈🎣🪣', wordHint: 'small' },
	{ itemName: 'Sacred eel', emojiHint: '🐍✨🌊🎣💎', wordHint: 'scales' },

	// ============================================================
	// SEEDS & FARMING
	// ============================================================
	{ itemName: 'Potato seed', emojiHint: '🥔🌱🌾🚜🌿', wordHint: 'allot' },
	{ itemName: 'Onion seed', emojiHint: '🧅🌱🌾😢🚜', wordHint: 'allot' },
	{ itemName: 'Cabbage seed', emojiHint: '🥬🌱🌾🟢🚜', wordHint: 'allot' },
	{ itemName: 'Tomato seed', emojiHint: '🍅🌱🌾🔴🚜', wordHint: 'allot' },
	{ itemName: 'Strawberry seed', emojiHint: '🍓🌱🌾🔴🚜', wordHint: 'fruit' },
	{ itemName: 'Watermelon seed', emojiHint: '🍉🌱🌾🟢🚜', wordHint: 'melon' },
	{ itemName: 'Snape grass seed', emojiHint: '🌿🌱🌾🧪🚜', wordHint: 'potion' },
	{ itemName: 'Marigold seed', emojiHint: '🌼🌱🌾🦋🚜', wordHint: 'allot' },
	{ itemName: 'Rosemary seed', emojiHint: '🌹🌱🌾🚜🌿', wordHint: 'allot' },
	{ itemName: 'Nasturtium seed', emojiHint: '🌸🌱🌾🐛🚜', wordHint: 'allot' },
	{ itemName: 'Woad seed', emojiHint: '🔵🌱🌾🎨🚜', wordHint: 'dye' },
	{ itemName: 'Limpwurt seed', emojiHint: '🔴🌱🌾🧪🚜', wordHint: 'potion' },
	{ itemName: 'Guam seed', emojiHint: '🌿🌱🧪🌾🚜', wordHint: 'herby' },
	{ itemName: 'Marrentill seed', emojiHint: '🌿🌱🧪🌾🚜', wordHint: 'herby' },
	{ itemName: 'Tarromin seed', emojiHint: '🌿🌱🧪🌾🚜', wordHint: 'herby' },
	{ itemName: 'Harralander seed', emojiHint: '🌿🌱🧪🌾🚜', wordHint: 'herby' },
	{ itemName: 'Ranarr seed', emojiHint: '🌿🌱🧪💎🚜', wordHint: 'pray' },
	{ itemName: 'Toadflax seed', emojiHint: '🐸🌱🌿🧪🚜', wordHint: 'herby' },
	{ itemName: 'Irit seed', emojiHint: '🌿🌱🧪🌾🚜', wordHint: 'herby' },
	{ itemName: 'Avantoe seed', emojiHint: '🌿🌱🧪🌾🚜', wordHint: 'herby' },
	{ itemName: 'Kwuarm seed', emojiHint: '🌿🌱🧪🌾🚜', wordHint: 'herby' },
	{ itemName: 'Snapdragon seed', emojiHint: '🌿🌱🧪💎🚜', wordHint: 'snap' },
	{ itemName: 'Cadantine seed', emojiHint: '🌿🌱🧪🌾🚜', wordHint: 'herby' },
	{ itemName: 'Lantadyme seed', emojiHint: '🌿🌱🧪🌾🚜', wordHint: 'herby' },
	{ itemName: 'Dwarf weed seed', emojiHint: '🌿🌱🧪🌾🚜', wordHint: 'herby' },
	{ itemName: 'Torstol seed', emojiHint: '🌿🌱🧪💎🚜', wordHint: 'super' },
	{ itemName: 'Acorn', emojiHint: '🌰🌳🌱🐿️🌲', wordHint: 'oaktree' },
	{ itemName: 'Willow seed', emojiHint: '🌿💧🌱🌳🌲', wordHint: 'droop' },
	{ itemName: 'Maple seed', emojiHint: '🍁🌱🌳🍬🌲', wordHint: 'syrup' },
	{ itemName: 'Yew seed', emojiHint: '🏹🌱🌳🌲🔝', wordHint: 'arrow' },
	{ itemName: 'Magic seed', emojiHint: '✨🌱🌳🔮🌲', wordHint: 'spell' },
	{ itemName: 'Dragonfruit tree seed', emojiHint: '🐉🍈🌱🌳🌲', wordHint: 'dragon' },
	{ itemName: 'Spirit seed', emojiHint: '👻🌱🌳🌲✨', wordHint: 'ghost' },
	{ itemName: 'Celastrus seed', emojiHint: '🌲🌱🏹🌳✨', wordHint: 'staff' },
	{ itemName: 'Redwood tree seed', emojiHint: '🔴🌲🌱🌳🏆', wordHint: 'giant' },
	{ itemName: 'Apple tree seed', emojiHint: '🍎🌱🌳🌲🍏', wordHint: 'fruit' },
	{ itemName: 'Banana tree seed', emojiHint: '🍌🌱🌳🌴🐒', wordHint: 'fruit' },
	{ itemName: 'Orange tree seed', emojiHint: '🍊🌱🌳🌲🎃', wordHint: 'fruit' },
	{ itemName: 'Curry tree seed', emojiHint: '🍛🌱🌳🌶️🌲', wordHint: 'spice' },
	{ itemName: 'Pineapple seed', emojiHint: '🍍🌱🌳🌴🌲', wordHint: 'fruit' },
	{ itemName: 'Papaya tree seed', emojiHint: '🍈🌱🌳🌴🌲', wordHint: 'fruit' },
	{ itemName: 'Palm tree seed', emojiHint: '🌴🌱🌳🏝️🌲', wordHint: 'tropic' },
	{ itemName: 'Mushroom spore', emojiHint: '🍄🌱🌿🟤🚜', wordHint: 'fungi' },
	{ itemName: 'Belladonna seed', emojiHint: '☠️🌱🌿🖤🚜', wordHint: 'deadly' },
	{ itemName: 'Cactus seed', emojiHint: '🌵🌱🌿🟢🚜', wordHint: 'spine' },
	{ itemName: 'Calquat tree seed', emojiHint: '🌴🌱🌲🏝️🌿', wordHint: 'tropic' },
	{ itemName: 'Hops seed', emojiHint: '🌾🌱🍺🌿🚜', wordHint: 'brew' },
	{ itemName: 'Barley seed', emojiHint: '🌾🌱🍺🟡🚜', wordHint: 'brew' },
	{ itemName: 'Hammerstone seed', emojiHint: '🌾🌱🍺🔨🚜', wordHint: 'brew' },
	{ itemName: 'Asgarnian hops seed', emojiHint: '🌾🌱🍺🏰🚜', wordHint: 'brew' },
	{ itemName: 'Jute seed', emojiHint: '🌾🌱🧵🟡🚜', wordHint: 'fiber' },
	{ itemName: 'Wildblood seed', emojiHint: '🌾🌱🍺🩸🚜', wordHint: 'brew' },
	{ itemName: 'Seaweed spore', emojiHint: '🌿🌊🌱🟢🚜', wordHint: 'ocean' },
	{ itemName: 'Kronos seed', emojiHint: '⏰🌱🌿✨🚜', wordHint: 'time' },
	{ itemName: 'Iasor seed', emojiHint: '🌱🌿✨🚜🍀', wordHint: 'grace' },
	{ itemName: 'Attas seed', emojiHint: '🌱🌿✨🚜🍀', wordHint: 'yield' },

	// ============================================================
	// HERBS (GRIMY & CLEAN)
	// ============================================================
	{ itemName: 'Grimy guam leaf', emojiHint: '🌿🤢🧪🟢💊', wordHint: 'dirty' },
	{ itemName: 'Grimy marrentill', emojiHint: '🌿🤢🧪🟢💊', wordHint: 'dirty' },
	{ itemName: 'Grimy tarromin', emojiHint: '🌿🤢🧪🟢💊', wordHint: 'dirty' },
	{ itemName: 'Grimy harralander', emojiHint: '🌿🤢🧪🟢💊', wordHint: 'dirty' },
	{ itemName: 'Grimy ranarr weed', emojiHint: '🌿🤢🧪💎💊', wordHint: 'dirty' },
	{ itemName: 'Grimy toadflax', emojiHint: '🌿🤢🐸🧪💊', wordHint: 'dirty' },
	{ itemName: 'Grimy irit leaf', emojiHint: '🌿🤢🧪🌾💊', wordHint: 'dirty' },
	{ itemName: 'Grimy avantoe', emojiHint: '🌿🤢🧪🌾💊', wordHint: 'dirty' },
	{ itemName: 'Grimy kwuarm', emojiHint: '🌿🤢🧪🌾💊', wordHint: 'dirty' },
	{ itemName: 'Grimy snapdragon', emojiHint: '🌿🤢🐉🧪💊', wordHint: 'dirty' },
	{ itemName: 'Grimy cadantine', emojiHint: '🌿🤢🧪🌾💊', wordHint: 'dirty' },
	{ itemName: 'Grimy lantadyme', emojiHint: '🌿🤢🧪🌾💊', wordHint: 'dirty' },
	{ itemName: 'Grimy dwarf weed', emojiHint: '🌿🤢🧪🌾💊', wordHint: 'dirty' },
	{ itemName: 'Grimy torstol', emojiHint: '🌿🤢🧪💎💊', wordHint: 'dirty' },
	{ itemName: 'Guam leaf', emojiHint: '🌿✨🧪🟢💊', wordHint: 'clean' },
	{ itemName: 'Marrentill', emojiHint: '🌿✨🧪🟢💊', wordHint: 'clean' },
	{ itemName: 'Tarromin', emojiHint: '🌿✨🧪🟢💊', wordHint: 'clean' },
	{ itemName: 'Harralander', emojiHint: '🌿✨🧪🟢💊', wordHint: 'clean' },
	{ itemName: 'Ranarr weed', emojiHint: '🌿✨🧪💎💊', wordHint: 'pray' },
	{ itemName: 'Toadflax', emojiHint: '🐸🌿✨🧪💊', wordHint: 'clean' },
	{ itemName: 'Irit leaf', emojiHint: '🌿✨🧪🌾💊', wordHint: 'clean' },
	{ itemName: 'Avantoe', emojiHint: '🌿✨🧪🌾💊', wordHint: 'clean' },
	{ itemName: 'Kwuarm', emojiHint: '🌿✨🧪🌾💊', wordHint: 'clean' },
	{ itemName: 'Snapdragon', emojiHint: '🐉🌿✨🧪💊', wordHint: 'snap' },
	{ itemName: 'Cadantine', emojiHint: '🌿✨🧪🌾💊', wordHint: 'clean' },
	{ itemName: 'Lantadyme', emojiHint: '🌿✨🧪🌾💊', wordHint: 'clean' },
	{ itemName: 'Dwarf weed', emojiHint: '🌿✨🧪🌾💊', wordHint: 'clean' },
	{ itemName: 'Torstol', emojiHint: '🌿✨🧪💎💊', wordHint: 'super' },

	// ============================================================
	// POTIONS
	// ============================================================
	{ itemName: 'Attack potion', emojiHint: '⚔️🧪💊🟠⬆️', wordHint: 'boost' },
	{ itemName: 'Strength potion', emojiHint: '💪🧪💊🟠⬆️', wordHint: 'boost' },
	{ itemName: 'Defence potion', emojiHint: '🛡️🧪💊🟠⬆️', wordHint: 'boost' },
	{ itemName: 'Ranging potion', emojiHint: '🏹🧪💊🟠⬆️', wordHint: 'boost' },
	{ itemName: 'Magic potion', emojiHint: '🔮🧪💊🟠⬆️', wordHint: 'boost' },
	{ itemName: 'Prayer potion', emojiHint: '🙏🧪💊🟡⬆️', wordHint: 'pray' },
	{ itemName: 'Super attack', emojiHint: '⚔️🧪💊🔴⬆️', wordHint: 'super' },
	{ itemName: 'Super strength', emojiHint: '💪🧪💊🔴⬆️', wordHint: 'super' },
	{ itemName: 'Super defence', emojiHint: '🛡️🧪💊🔴⬆️', wordHint: 'super' },
	{ itemName: 'Super ranging', emojiHint: '🏹🧪💊🔴⬆️', wordHint: 'super' },
	{ itemName: 'Super magic', emojiHint: '🔮🧪💊🔴⬆️', wordHint: 'super' },
	{ itemName: 'Super combat potion', emojiHint: '⚔️💪🧪💊🔴', wordHint: 'combo' },
	{ itemName: 'Antidote+', emojiHint: '☠️🧪💊🟢🐍', wordHint: 'venom' },
	{ itemName: 'Antidote++', emojiHint: '☠️🧪💊🟢🐍', wordHint: 'venom' },
	{ itemName: 'Antipoison', emojiHint: '🐍🧪💊🟢⛑️', wordHint: 'cure' },
	{ itemName: 'Anti-venom', emojiHint: '🐍🧪💊💚⛑️', wordHint: 'venom' },
	{ itemName: 'Anti-venom+', emojiHint: '🐍🧪💊💚⛑️', wordHint: 'venom' },
	{ itemName: 'Restore potion', emojiHint: '⬆️🧪💊🟡🔄', wordHint: 'stats' },
	{ itemName: 'Super restore', emojiHint: '⬆️🧪💊🔴🔄', wordHint: 'stats' },
	{ itemName: 'Sanfew serum', emojiHint: '🐍⬆️🧪💊✨', wordHint: 'serum' },
	{ itemName: 'Energy potion', emojiHint: '⚡🧪💊🟡🏃', wordHint: 'run' },
	{ itemName: 'Super energy', emojiHint: '⚡🧪💊🔴🏃', wordHint: 'super' },
	{ itemName: 'Stamina potion', emojiHint: '🏃⚡🧪💊🟣', wordHint: 'endure' },
	{ itemName: 'Agility potion', emojiHint: '🤸🧪💊🟠⬆️', wordHint: 'boost' },
	{ itemName: 'Combat potion', emojiHint: '⚔️🛡️🧪💊🟠', wordHint: 'fight' },
	{ itemName: 'Fishing potion', emojiHint: '🎣🧪💊🟠⬆️', wordHint: 'boost' },
	{ itemName: 'Hunter potion', emojiHint: '🏹🌿🧪💊⬆️', wordHint: 'boost' },
	{ itemName: 'Fletching potion', emojiHint: '🏹🪵🧪💊⬆️', wordHint: 'boost' },
	{ itemName: 'Crafting potion', emojiHint: '💍🧪💊🟠⬆️', wordHint: 'boost' },
	{ itemName: 'Farming potion', emojiHint: '🌱🧪💊🟠⬆️', wordHint: 'boost' },
	{ itemName: 'Herblore potion', emojiHint: '🌿🧪💊🟠⬆️', wordHint: 'boost' },
	{ itemName: 'Smithing potion', emojiHint: '⚒️🧪💊🟠⬆️', wordHint: 'boost' },
	{ itemName: 'Mining potion', emojiHint: '⛏️🧪💊🟠⬆️', wordHint: 'boost' },
	{ itemName: 'Saradomin brew', emojiHint: '☀️🧪💊🩹🙏', wordHint: 'heal' },
	{ itemName: 'Zamorak brew', emojiHint: '🔴🧪💊⚔️😈', wordHint: 'chaos' },
	{ itemName: 'Ancient brew', emojiHint: '🏛️🧪💊🔵🔮', wordHint: 'magic' },
	{ itemName: 'Imbued heart', emojiHint: '❤️🔮✨💜🧙', wordHint: 'magic' },
	{ itemName: 'Bastion potion', emojiHint: '🛡️🏹🧪💊⬆️', wordHint: 'range' },
	{ itemName: 'Battlemage potion', emojiHint: '🔮🛡️🧪💊⬆️', wordHint: 'magic' },
	{ itemName: 'Divine super combat', emojiHint: '✨⚔️💪🧪💊', wordHint: 'divine' },
	{ itemName: 'Extended antifire', emojiHint: '🔥🛡️🧪💊🐉', wordHint: 'fire' },
	{ itemName: 'Antifire potion', emojiHint: '🔥🛡️🧪💊🐉', wordHint: 'fire' },
	{ itemName: 'Super antifire', emojiHint: '🔥🛡️🧪💊🐉', wordHint: 'fire' },
	{ itemName: 'Overload', emojiHint: '💥🧪💊🔴⚡', wordHint: 'raids' },

	// ============================================================
	// RUNES
	// ============================================================
	{ itemName: 'Air rune', emojiHint: '💨🔮🌀⭕✨', wordHint: 'spell' },
	{ itemName: 'Water rune', emojiHint: '💧🔮🌀⭕✨', wordHint: 'spell' },
	{ itemName: 'Earth rune', emojiHint: '🌍🔮🌀⭕✨', wordHint: 'spell' },
	{ itemName: 'Fire rune', emojiHint: '🔥🔮🌀⭕✨', wordHint: 'spell' },
	{ itemName: 'Mind rune', emojiHint: '🧠🔮🌀⭕✨', wordHint: 'spell' },
	{ itemName: 'Body rune', emojiHint: '🫀🔮🌀⭕✨', wordHint: 'spell' },
	{ itemName: 'Cosmic rune', emojiHint: '🌌🔮🌀⭕✨', wordHint: 'spell' },
	{ itemName: 'Chaos rune', emojiHint: '💥🔮🌀⭕✨', wordHint: 'spell' },
	{ itemName: 'Nature rune', emojiHint: '🌿🔮🌀⭕✨', wordHint: 'alch' },
	{ itemName: 'Law rune', emojiHint: '⚖️🔮🌀⭕✨', wordHint: 'teleport' },
	{ itemName: 'Death rune', emojiHint: '💀🔮🌀⭕✨', wordHint: 'spell' },
	{ itemName: 'Blood rune', emojiHint: '🩸🔮🌀⭕✨', wordHint: 'spell' },
	{ itemName: 'Soul rune', emojiHint: '👻🔮🌀⭕✨', wordHint: 'spell' },
	{ itemName: 'Wrath rune', emojiHint: '😡🔮🌀⭕✨', wordHint: 'spell' },
	{ itemName: 'Astral rune', emojiHint: '⭐🔮🌀⭕✨', wordHint: 'lunar' },
	{ itemName: 'Mist rune', emojiHint: '🌫️🔮🌀⭕✨', wordHint: 'combo' },
	{ itemName: 'Mud rune', emojiHint: '🟫🔮🌀⭕✨', wordHint: 'combo' },
	{ itemName: 'Steam rune', emojiHint: '♨️🔮🌀⭕✨', wordHint: 'combo' },
	{ itemName: 'Smoke rune', emojiHint: '🌫️🔥🔮🌀⭕', wordHint: 'combo' },
	{ itemName: 'Lava rune', emojiHint: '🌋🔮🌀⭕✨', wordHint: 'combo' },
	{ itemName: 'Dust rune', emojiHint: '🌪️🔮🌀⭕✨', wordHint: 'combo' },

	// ============================================================
	// ARROWS & BOLTS
	// ============================================================
	{ itemName: 'Bronze arrow', emojiHint: '🏹🟫🔩⬆️🎯', wordHint: 'shoot' },
	{ itemName: 'Iron arrow', emojiHint: '🏹⚫🔩⬆️🎯', wordHint: 'shoot' },
	{ itemName: 'Steel arrow', emojiHint: '🏹⚙️🔩⬆️🎯', wordHint: 'shoot' },
	{ itemName: 'Mithril arrow', emojiHint: '🏹🔵🔩⬆️🎯', wordHint: 'shoot' },
	{ itemName: 'Adamant arrow', emojiHint: '🏹🟢🔩⬆️🎯', wordHint: 'shoot' },
	{ itemName: 'Rune arrow', emojiHint: '🏹🩵🔩⬆️🎯', wordHint: 'shoot' },
	{ itemName: 'Dragon arrow', emojiHint: '🏹🐉🔩⬆️🎯', wordHint: 'shoot' },
	{ itemName: 'Amethyst arrow', emojiHint: '🏹💜🔩⬆️🎯', wordHint: 'shoot' },
	{ itemName: 'Broad arrow', emojiHint: '🏹🌿🔩⬆️🎯', wordHint: 'slayer' },
	{ itemName: 'Bronze bolts', emojiHint: '🔩🟫🏹⬆️🎯', wordHint: 'xbow' },
	{ itemName: 'Iron bolts', emojiHint: '🔩⚫🏹⬆️🎯', wordHint: 'xbow' },
	{ itemName: 'Steel bolts', emojiHint: '🔩⚙️🏹⬆️🎯', wordHint: 'xbow' },
	{ itemName: 'Mithril bolts', emojiHint: '🔩🔵🏹⬆️🎯', wordHint: 'xbow' },
	{ itemName: 'Adamant bolts', emojiHint: '🔩🟢🏹⬆️🎯', wordHint: 'xbow' },
	{ itemName: 'Runite bolts', emojiHint: '🔩🩵🏹⬆️🎯', wordHint: 'xbow' },
	{ itemName: 'Dragon bolts', emojiHint: '🔩🐉🏹⬆️🎯', wordHint: 'xbow' },
	{ itemName: 'Broad bolts', emojiHint: '🔩🌿🏹⬆️🎯', wordHint: 'slayer' },
	{ itemName: 'Opal bolts (e)', emojiHint: '🔩💎🏹⬆️🎯', wordHint: 'ench' },
	{ itemName: 'Pearl bolts (e)', emojiHint: '🔩🌊🏹⬆️🎯', wordHint: 'ench' },
	{ itemName: 'Emerald bolts (e)', emojiHint: '🔩🟢🏹⬆️🎯', wordHint: 'ench' },
	{ itemName: 'Ruby bolts (e)', emojiHint: '🔩🔴🏹⬆️🎯', wordHint: 'ench' },
	{ itemName: 'Diamond bolts (e)', emojiHint: '🔩💠🏹⬆️🎯', wordHint: 'ench' },
	{ itemName: 'Dragonstone bolts (e)', emojiHint: '🔩🐉🏹💎🎯', wordHint: 'ench' },
	{ itemName: 'Onyx bolts (e)', emojiHint: '🔩⚫🏹💎🎯', wordHint: 'ench' },
	{ itemName: 'Amethyst broad bolts', emojiHint: '🔩💜🏹🌿🎯', wordHint: 'slayer' },

	// ============================================================
	// BOWS & CROSSBOWS
	// ============================================================
	{ itemName: 'Shortbow', emojiHint: '🏹🪵🟤⬆️🎯', wordHint: 'shoot' },
	{ itemName: 'Longbow', emojiHint: '🏹🪵🟤⬇️🎯', wordHint: 'shoot' },
	{ itemName: 'Oak shortbow', emojiHint: '🏹🌳🟤⬆️🎯', wordHint: 'shoot' },
	{ itemName: 'Oak longbow', emojiHint: '🏹🌳🟤⬇️🎯', wordHint: 'shoot' },
	{ itemName: 'Willow shortbow', emojiHint: '🏹🌿🟤⬆️🎯', wordHint: 'shoot' },
	{ itemName: 'Willow longbow', emojiHint: '🏹🌿🟤⬇️🎯', wordHint: 'shoot' },
	{ itemName: 'Maple shortbow', emojiHint: '🏹🍁🟤⬆️🎯', wordHint: 'shoot' },
	{ itemName: 'Maple longbow', emojiHint: '🏹🍁🟤⬇️🎯', wordHint: 'shoot' },
	{ itemName: 'Yew shortbow', emojiHint: '🏹🌲🟤⬆️🎯', wordHint: 'shoot' },
	{ itemName: 'Yew longbow', emojiHint: '🏹🌲🟤⬇️🎯', wordHint: 'shoot' },
	{ itemName: 'Magic shortbow', emojiHint: '🏹✨🟤⬆️🎯', wordHint: 'shoot' },
	{ itemName: 'Magic longbow', emojiHint: '🏹✨🟤⬇️🎯', wordHint: 'shoot' },
	{ itemName: 'Magic shortbow (i)', emojiHint: '🏹✨🌟⬆️🎯', wordHint: 'imbue' },
	{ itemName: 'Crossbow', emojiHint: '🔩🏹🪵🎯⚙️', wordHint: 'xbow' },
	{ itemName: 'Bronze crossbow', emojiHint: '🔩🏹🟫🎯⚙️', wordHint: 'xbow' },
	{ itemName: 'Iron crossbow', emojiHint: '🔩🏹⚫🎯⚙️', wordHint: 'xbow' },
	{ itemName: 'Steel crossbow', emojiHint: '🔩🏹⚙️🎯⚙️', wordHint: 'xbow' },
	{ itemName: 'Mithril crossbow', emojiHint: '🔩🏹🔵🎯⚙️', wordHint: 'xbow' },
	{ itemName: 'Adamant crossbow', emojiHint: '🔩🏹🟢🎯⚙️', wordHint: 'xbow' },
	{ itemName: 'Rune crossbow', emojiHint: '🔩🏹🩵🎯⚙️', wordHint: 'xbow' },
	{ itemName: 'Dragon crossbow', emojiHint: '🔩🏹🐉🎯⚙️', wordHint: 'xbow' },
	{ itemName: 'Armadyl crossbow', emojiHint: '🦅🔩🏹🎯⚙️', wordHint: 'xbow' },
	{ itemName: 'Zaryte crossbow', emojiHint: '🏛️🔩🏹🎯⚙️', wordHint: 'xbow' },
	{ itemName: 'Ballista', emojiHint: '🏹🔩💥⚙️🎯', wordHint: 'heavy' },
	{ itemName: 'Heavy ballista', emojiHint: '🏹🔩💥⚙️🏆', wordHint: 'heavy' },
	{ itemName: 'Light ballista', emojiHint: '🏹🔩💨⚙️🎯', wordHint: 'light' },
	{ itemName: 'Crystal bow', emojiHint: '💎🏹✨🧝🎯', wordHint: 'elf' },
	{ itemName: 'Bow of faerdhinen', emojiHint: '💎🏹✨🧝🌟', wordHint: 'elf' },
	{ itemName: 'Twisted bow', emojiHint: '🏹🌀🏆🎯💎', wordHint: 'raids' },
	{ itemName: 'Chinchompa', emojiHint: '🐹💥🏹🌿🎯', wordHint: 'hunter' },
	{ itemName: 'Red chinchompa', emojiHint: '🔴🐹💥🏹🎯', wordHint: 'hunter' },
	{ itemName: 'Black chinchompa', emojiHint: '⚫🐹💥🏹🎯', wordHint: 'wilds' },
	{ itemName: 'Blowpipe', emojiHint: '🎋💨🏹🐍🎯', wordHint: 'scales' },
	{ itemName: 'Toxic blowpipe', emojiHint: '☠️🎋💨🐍🎯', wordHint: 'venom' },
	{ itemName: 'Dark bow', emojiHint: '🖤🏹✨🐉🎯', wordHint: 'dragon' },
	{ itemName: "Karil's crossbow", emojiHint: '⚰️🔩🏹🎯⚙️', wordHint: 'barrows' },
	{ itemName: "Craw's bow", emojiHint: '🌿🏹✨⚡🎯', wordHint: 'wilds' },
	{ itemName: 'Webweaver bow', emojiHint: '🕸️🏹✨⚡🎯', wordHint: 'wilds' },

	// ============================================================
	// STAVES & WANDS
	// ============================================================
	{ itemName: 'Staff', emojiHint: '🪄🔮🌀🌿🟤', wordHint: 'magic' },
	{ itemName: 'Magic staff', emojiHint: '🪄🔮🌀✨🟤', wordHint: 'magic' },
	{ itemName: 'Staff of air', emojiHint: '🪄💨🔮🌀⭕', wordHint: 'magic' },
	{ itemName: 'Staff of water', emojiHint: '🪄💧🔮🌀⭕', wordHint: 'magic' },
	{ itemName: 'Staff of earth', emojiHint: '🪄🌍🔮🌀⭕', wordHint: 'magic' },
	{ itemName: 'Staff of fire', emojiHint: '🪄🔥🔮🌀⭕', wordHint: 'magic' },
	{ itemName: 'Battlestaff', emojiHint: '🪄⚔️🔮🌀⭕', wordHint: 'magic' },
	{ itemName: 'Air battlestaff', emojiHint: '🪄💨⚔️🔮🌀', wordHint: 'magic' },
	{ itemName: 'Water battlestaff', emojiHint: '🪄💧⚔️🔮🌀', wordHint: 'magic' },
	{ itemName: 'Earth battlestaff', emojiHint: '🪄🌍⚔️🔮🌀', wordHint: 'magic' },
	{ itemName: 'Fire battlestaff', emojiHint: '🪄🔥⚔️🔮🌀', wordHint: 'magic' },
	{ itemName: 'Mystic air staff', emojiHint: '🪄💨✨🔮🌀', wordHint: 'mystic' },
	{ itemName: 'Mystic water staff', emojiHint: '🪄💧✨🔮🌀', wordHint: 'mystic' },
	{ itemName: 'Mystic earth staff', emojiHint: '🪄🌍✨🔮🌀', wordHint: 'mystic' },
	{ itemName: 'Mystic fire staff', emojiHint: '🪄🔥✨🔮🌀', wordHint: 'mystic' },
	{ itemName: "Slayer's staff", emojiHint: '🪄💀🔮🌀🗡️', wordHint: 'slay' },
	{ itemName: 'Ancient staff', emojiHint: '🏛️🪄🔮🌀🗡️', wordHint: 'kharyll' },
	{ itemName: 'Void knight mace', emojiHint: '🪄⚒️🔮🌀⚪', wordHint: 'void' },
	{ itemName: 'Kodai wand', emojiHint: '🪄💧✨🏆🔮', wordHint: 'raids' },
	{ itemName: 'Nightmare staff', emojiHint: '🪄😱🔮✨🌙', wordHint: 'night' },
	{ itemName: 'Eldritch nightmare staff', emojiHint: '🪄😱🔮💜🌙', wordHint: 'night' },
	{ itemName: 'Volatile nightmare staff', emojiHint: '🪄😱💥🔮🌙', wordHint: 'night' },
	{ itemName: 'Harmonised nightmare staff', emojiHint: '🪄😱🎵🔮🌙', wordHint: 'night' },
	{ itemName: 'Trident of the seas', emojiHint: '🔱🌊🪄🔮🐙', wordHint: 'seas' },
	{ itemName: 'Trident of the swamp', emojiHint: '🔱🌿🪄🔮☠️', wordHint: 'swamp' },
	{ itemName: 'Sanguinesti staff', emojiHint: '🩸🪄🔮💀✨', wordHint: 'blood' },
	{ itemName: "Tumeken's shadow", emojiHint: '🌑🪄🔮✨🏛️', wordHint: 'toa' },
	{ itemName: 'Crystal staff', emojiHint: '💎🪄✨🧝🔮', wordHint: 'elf' },
	{ itemName: 'Accursed sceptre', emojiHint: '☠️🪄🔮⚡🌑', wordHint: 'wilds' },
	{ itemName: "Thammaron's sceptre", emojiHint: '👹🪄🔮⚡🌑', wordHint: 'wilds' },
	{ itemName: 'Starter staff', emojiHint: '🪄🔮🌀⭕🆕', wordHint: 'magic' },

	// ============================================================
	// SWORDS & DAGGERS
	// ============================================================
	{ itemName: 'Bronze dagger', emojiHint: '🗡️🟫🔩⚔️🆕', wordHint: 'stab' },
	{ itemName: 'Iron dagger', emojiHint: '🗡️⚫🔩⚔️🆕', wordHint: 'stab' },
	{ itemName: 'Steel dagger', emojiHint: '🗡️⚙️🔩⚔️🆕', wordHint: 'stab' },
	{ itemName: 'Black dagger', emojiHint: '🗡️🖤🔩⚔️🆕', wordHint: 'stab' },
	{ itemName: 'Mithril dagger', emojiHint: '🗡️🔵🔩⚔️🆕', wordHint: 'stab' },
	{ itemName: 'Adamant dagger', emojiHint: '🗡️🟢🔩⚔️🆕', wordHint: 'stab' },
	{ itemName: 'Rune dagger', emojiHint: '🗡️🩵🔩⚔️🆕', wordHint: 'stab' },
	{ itemName: 'Dragon dagger', emojiHint: '🗡️🐉🔩⚔️🏆', wordHint: 'spec' },
	{ itemName: 'Dragon dagger (p++)', emojiHint: '🗡️🐉🐍⚔️💀', wordHint: 'poison' },
	{ itemName: 'Abyssal dagger', emojiHint: '🗡️🕳️💀⚔️🏆', wordHint: 'abyss' },
	{ itemName: 'Bronze sword', emojiHint: '⚔️🟫🔩🛡️🆕', wordHint: 'slash' },
	{ itemName: 'Iron sword', emojiHint: '⚔️⚫🔩🛡️🆕', wordHint: 'slash' },
	{ itemName: 'Steel sword', emojiHint: '⚔️⚙️🔩🛡️🆕', wordHint: 'slash' },
	{ itemName: 'Black sword', emojiHint: '⚔️🖤🔩🛡️🆕', wordHint: 'slash' },
	{ itemName: 'Mithril sword', emojiHint: '⚔️🔵🔩🛡️🆕', wordHint: 'slash' },
	{ itemName: 'Adamant sword', emojiHint: '⚔️🟢🔩🛡️🆕', wordHint: 'slash' },
	{ itemName: 'Rune sword', emojiHint: '⚔️🩵🔩🛡️🆕', wordHint: 'slash' },
	{ itemName: 'Bronze scimitar', emojiHint: '⚔️🟫🌙🛡️🆕', wordHint: 'slash' },
	{ itemName: 'Iron scimitar', emojiHint: '⚔️⚫🌙🛡️🆕', wordHint: 'slash' },
	{ itemName: 'Steel scimitar', emojiHint: '⚔️⚙️🌙🛡️🆕', wordHint: 'slash' },
	{ itemName: 'Black scimitar', emojiHint: '⚔️🖤🌙🛡️🆕', wordHint: 'slash' },
	{ itemName: 'Mithril scimitar', emojiHint: '⚔️🔵🌙🛡️🆕', wordHint: 'slash' },
	{ itemName: 'Adamant scimitar', emojiHint: '⚔️🟢🌙🛡️🆕', wordHint: 'slash' },
	{ itemName: 'Rune scimitar', emojiHint: '⚔️🩵🌙🛡️🆕', wordHint: 'slash' },
	{ itemName: 'Dragon scimitar', emojiHint: '⚔️🐉🌙🛡️🏆', wordHint: 'slash' },
	{ itemName: 'Bronze longsword', emojiHint: '⚔️🟫🔩🛡️🔝', wordHint: 'slash' },
	{ itemName: 'Iron longsword', emojiHint: '⚔️⚫🔩🛡️🔝', wordHint: 'slash' },
	{ itemName: 'Steel longsword', emojiHint: '⚔️⚙️🔩🛡️🔝', wordHint: 'slash' },
	{ itemName: 'Mithril longsword', emojiHint: '⚔️🔵🔩🛡️🔝', wordHint: 'slash' },
	{ itemName: 'Adamant longsword', emojiHint: '⚔️🟢🔩🛡️🔝', wordHint: 'slash' },
	{ itemName: 'Rune longsword', emojiHint: '⚔️🩵🔩🛡️🔝', wordHint: 'slash' },
	{ itemName: 'Dragon longsword', emojiHint: '⚔️🐉🔩🛡️🏆', wordHint: 'spec' },
	{ itemName: 'Bronze 2h sword', emojiHint: '⚔️🟫🔩💪🔝', wordHint: 'crush' },
	{ itemName: 'Iron 2h sword', emojiHint: '⚔️⚫🔩💪🔝', wordHint: 'crush' },
	{ itemName: 'Steel 2h sword', emojiHint: '⚔️⚙️🔩💪🔝', wordHint: 'crush' },
	{ itemName: 'Mithril 2h sword', emojiHint: '⚔️🔵🔩💪🔝', wordHint: 'crush' },
	{ itemName: 'Adamant 2h sword', emojiHint: '⚔️🟢🔩💪🔝', wordHint: 'crush' },
	{ itemName: 'Rune 2h sword', emojiHint: '⚔️🩵🔩💪🔝', wordHint: 'crush' },
	{ itemName: 'Dragon 2h sword', emojiHint: '⚔️🐉🔩💪🏆', wordHint: 'crush' },
	{ itemName: 'Saradomin sword', emojiHint: '☀️⚔️🙏🛡️✨', wordHint: 'sara' },
	{ itemName: 'Zamorak sword', emojiHint: '🔴⚔️😈🛡️✨', wordHint: 'zammy' },
	{ itemName: 'Blessed sword', emojiHint: '✝️⚔️🙏✨🛡️', wordHint: 'holy' },
	{ itemName: "Korasi's sword", emojiHint: '🌀⚔️💙✨🛡️', wordHint: 'spec' },
	{ itemName: "Osmumten's fang", emojiHint: '🐍⚔️🏛️✨🏆', wordHint: 'toa' },
	{ itemName: 'Rapier', emojiHint: '🗡️🔵⚔️✨🏆', wordHint: 'raids' },
	{ itemName: 'Ghrazi rapier', emojiHint: '🗡️🔴⚔️✨🏆', wordHint: 'tob' },
	{ itemName: 'Blade of saeldor', emojiHint: '💎⚔️🧝✨🏆', wordHint: 'elf' },

	// ============================================================
	// AXES, MACES, HALBERDS, SPEARS
	// ============================================================
	{ itemName: 'Bronze axe', emojiHint: '🪓🟫🔩🌲⚔️', wordHint: 'chop' },
	{ itemName: 'Iron axe', emojiHint: '🪓⚫🔩🌲⚔️', wordHint: 'chop' },
	{ itemName: 'Steel axe', emojiHint: '🪓⚙️🔩🌲⚔️', wordHint: 'chop' },
	{ itemName: 'Black axe', emojiHint: '🪓🖤🔩🌲⚔️', wordHint: 'chop' },
	{ itemName: 'Mithril axe', emojiHint: '🪓🔵🔩🌲⚔️', wordHint: 'chop' },
	{ itemName: 'Adamant axe', emojiHint: '🪓🟢🔩🌲⚔️', wordHint: 'chop' },
	{ itemName: 'Rune axe', emojiHint: '🪓🩵🔩🌲⚔️', wordHint: 'chop' },
	{ itemName: 'Dragon axe', emojiHint: '🪓🐉🔩🌲⚔️', wordHint: 'spec' },
	{ itemName: 'Infernal axe', emojiHint: '🪓🌋🔥🌲⚔️', wordHint: 'infernal' },
	{ itemName: 'Crystal axe', emojiHint: '🪓💎✨🌲⚔️', wordHint: 'elf' },
	{ itemName: '3rd age axe', emojiHint: '🪓🏛️✨🌲🏆', wordHint: 'rare' },
	{ itemName: 'Bronze mace', emojiHint: '⚒️🟫🔩🙏⚔️', wordHint: 'crush' },
	{ itemName: 'Iron mace', emojiHint: '⚒️⚫🔩🙏⚔️', wordHint: 'crush' },
	{ itemName: 'Steel mace', emojiHint: '⚒️⚙️🔩🙏⚔️', wordHint: 'crush' },
	{ itemName: 'Mithril mace', emojiHint: '⚒️🔵🔩🙏⚔️', wordHint: 'crush' },
	{ itemName: 'Adamant mace', emojiHint: '⚒️🟢🔩🙏⚔️', wordHint: 'crush' },
	{ itemName: 'Rune mace', emojiHint: '⚒️🩵🔩🙏⚔️', wordHint: 'crush' },
	{ itemName: 'Dragon mace', emojiHint: '⚒️🐉🔩🙏⚔️', wordHint: 'spec' },
	{ itemName: 'Granite maul', emojiHint: '🪨⚒️💪💥⚔️', wordHint: 'spec' },
	{ itemName: 'Elder maul', emojiHint: '🌲⚒️💪💥🏆', wordHint: 'raids' },
	{ itemName: 'Abyssal bludgeon', emojiHint: '🕳️⚒️💀💥🏆', wordHint: 'abyss' },
	{ itemName: "Inquisitor's mace", emojiHint: '🔍⚒️💥✨🏆', wordHint: 'night' },
	{ itemName: 'Bronze halberd', emojiHint: '⚔️🟫🔩🏹🛡️', wordHint: 'range' },
	{ itemName: 'Iron halberd', emojiHint: '⚔️⚫🔩🏹🛡️', wordHint: 'range' },
	{ itemName: 'Steel halberd', emojiHint: '⚔️⚙️🔩🏹🛡️', wordHint: 'range' },
	{ itemName: 'Mithril halberd', emojiHint: '⚔️🔵🔩🏹🛡️', wordHint: 'range' },
	{ itemName: 'Adamant halberd', emojiHint: '⚔️🟢🔩🏹🛡️', wordHint: 'range' },
	{ itemName: 'Rune halberd', emojiHint: '⚔️🩵🔩🏹🛡️', wordHint: 'range' },
	{ itemName: 'Dragon halberd', emojiHint: '⚔️🐉🔩🏹🛡️', wordHint: 'spec' },
	{ itemName: 'Crystal halberd', emojiHint: '⚔️💎✨🏹🧝', wordHint: 'elf' },
	{ itemName: 'Hasta', emojiHint: '⚔️🔵🌊🗡️🐲', wordHint: 'slash' },
	{ itemName: 'Dragon hasta', emojiHint: '⚔️🐉🌊🗡️✨', wordHint: 'spec' },
	{ itemName: 'Zamorakian hasta', emojiHint: '⚔️🔴😈🌊🗡️', wordHint: 'gwd' },
	{ itemName: 'Spear', emojiHint: '⚔️🟤🔩🗡️🏹', wordHint: 'stab' },
	{ itemName: 'Dragon spear', emojiHint: '⚔️🐉🔩🗡️🏹', wordHint: 'spec' },
	{ itemName: 'Zamorakian spear', emojiHint: '⚔️🔴😈🗡️🏹', wordHint: 'gwd' },
	{ itemName: 'Soulreaper axe', emojiHint: '🪓💀👻✨🏆', wordHint: 'soul' },
	{ itemName: 'Zombie axe', emojiHint: '🪓🧟💀✨⚔️', wordHint: 'undead' },
	{ itemName: 'Scythe of vitur', emojiHint: '🌾💀🩸✨🏆', wordHint: 'tob' },
	{ itemName: 'Dual macuahuitl', emojiHint: '⚔️🦷💀✨🏆', wordHint: 'toa' },

	// ============================================================
	// SPECIAL / BOSS WEAPONS
	// ============================================================
	{ itemName: 'Abyssal whip', emojiHint: '🕳️🪱💀⚔️🏆', wordHint: 'abyss' },
	{ itemName: 'Tentacle whip', emojiHint: '🐙🕳️💀⚔️🏆', wordHint: 'whip' },
	{ itemName: 'Abyssal tentacle', emojiHint: '🐙🕳️💀⚔️✨', wordHint: 'whip' },
	{ itemName: 'Saradomin godsword', emojiHint: '☀️⚔️🙏✨🏆', wordHint: 'gwd' },
	{ itemName: 'Zamorak godsword', emojiHint: '🔴⚔️😈✨🏆', wordHint: 'gwd' },
	{ itemName: 'Bandos godsword', emojiHint: '🟤⚔️👺✨🏆', wordHint: 'gwd' },
	{ itemName: 'Armadyl godsword', emojiHint: '🦅⚔️☀️✨🏆', wordHint: 'gwd' },
	{ itemName: 'Ancient godsword', emojiHint: '🏛️⚔️❄️✨🏆', wordHint: 'gwd' },
	{ itemName: 'Zaryte vambraces', emojiHint: '🏛️🤜🏹✨🏆', wordHint: 'nex' },
	{ itemName: 'Noxious halberd', emojiHint: '☠️⚔️🌿🏹✨', wordHint: 'spec' },
	{ itemName: 'Dragon hunter lance', emojiHint: '🐉🗡️⚔️💎🏆', wordHint: 'dragon' },
	{ itemName: 'Dragon hunter crossbow', emojiHint: '🐉🔩🏹💎🏆', wordHint: 'dragon' },
	{ itemName: "Dinh's bulwark", emojiHint: '🛡️💪🔒⚔️🏆', wordHint: 'raids' },
	{ itemName: 'Keris partisan', emojiHint: '🗡️🔮🏛️✨🏆', wordHint: 'toa' },
	{ itemName: 'Bone dagger', emojiHint: '🗡️🦴💀✨🎯', wordHint: 'spec' },

	// ============================================================
	// PICKAXES
	// ============================================================
	{ itemName: 'Bronze pickaxe', emojiHint: '⛏️🟫🔩🪨💎', wordHint: 'mine' },
	{ itemName: 'Iron pickaxe', emojiHint: '⛏️⚫🔩🪨💎', wordHint: 'mine' },
	{ itemName: 'Steel pickaxe', emojiHint: '⛏️⚙️🔩🪨💎', wordHint: 'mine' },
	{ itemName: 'Black pickaxe', emojiHint: '⛏️🖤🔩🪨💎', wordHint: 'mine' },
	{ itemName: 'Mithril pickaxe', emojiHint: '⛏️🔵🔩🪨💎', wordHint: 'mine' },
	{ itemName: 'Adamant pickaxe', emojiHint: '⛏️🟢🔩🪨💎', wordHint: 'mine' },
	{ itemName: 'Rune pickaxe', emojiHint: '⛏️🩵🔩🪨💎', wordHint: 'mine' },
	{ itemName: 'Dragon pickaxe', emojiHint: '⛏️🐉🔩🪨💎', wordHint: 'spec' },
	{ itemName: 'Infernal pickaxe', emojiHint: '⛏️🌋🔥🪨💎', wordHint: 'infernal' },
	{ itemName: 'Crystal pickaxe', emojiHint: '⛏️💎✨🪨🧝', wordHint: 'elf' },
	{ itemName: '3rd age pickaxe', emojiHint: '⛏️🏛️✨🪨🏆', wordHint: 'rare' },
	{ itemName: 'Gilded pickaxe', emojiHint: '⛏️🟡✨🪨💎', wordHint: 'gilded' },

	// ============================================================
	// HELMETS
	// ============================================================
	{ itemName: 'Bronze full helm', emojiHint: '⛑️🟫🔩🛡️🆕', wordHint: 'helm' },
	{ itemName: 'Iron full helm', emojiHint: '⛑️⚫🔩🛡️🆕', wordHint: 'helm' },
	{ itemName: 'Steel full helm', emojiHint: '⛑️⚙️🔩🛡️🆕', wordHint: 'helm' },
	{ itemName: 'Black full helm', emojiHint: '⛑️🖤🔩🛡️🆕', wordHint: 'helm' },
	{ itemName: 'Mithril full helm', emojiHint: '⛑️🔵🔩🛡️🆕', wordHint: 'helm' },
	{ itemName: 'Adamant full helm', emojiHint: '⛑️🟢🔩🛡️🆕', wordHint: 'helm' },
	{ itemName: 'Rune full helm', emojiHint: '⛑️🩵🔩🛡️🆕', wordHint: 'helm' },
	{ itemName: 'Dragon full helm', emojiHint: '⛑️🐉🔩🛡️🏆', wordHint: 'dragon' },
	{ itemName: 'Helm of neitiznot', emojiHint: '⛑️🧝❄️🛡️✨', wordHint: 'quest' },
	{ itemName: 'Berserker helm', emojiHint: '⛑️💢🔴🛡️⚔️', wordHint: 'barb' },
	{ itemName: 'Warrior helm', emojiHint: '⛑️⚔️🛡️💪🔴', wordHint: 'barb' },
	{ itemName: 'Archer helm', emojiHint: '⛑️🏹🛡️🔴🎯', wordHint: 'barb' },
	{ itemName: 'Farseer helm', emojiHint: '⛑️🔮🛡️🔴👁️', wordHint: 'barb' },
	{ itemName: 'Serpentine helm', emojiHint: '⛑️🐍🌿🛡️✨', wordHint: 'zulrah' },
	{ itemName: 'Tanzanite helm', emojiHint: '⛑️🔵🐍🛡️✨', wordHint: 'zulrah' },
	{ itemName: 'Magma helm', emojiHint: '⛑️🌋🐍🛡️✨', wordHint: 'zulrah' },
	{ itemName: 'Slayer helmet', emojiHint: '⛑️💀🌿🛡️🔪', wordHint: 'slay' },
	{ itemName: 'Slayer helmet (i)', emojiHint: '⛑️💀✨🛡️🔪', wordHint: 'imbue' },
	{ itemName: 'Void melee helm', emojiHint: '⛑️⚪⚔️🛡️✨', wordHint: 'void' },
	{ itemName: 'Void ranger helm', emojiHint: '⛑️⚪🏹🛡️✨', wordHint: 'void' },
	{ itemName: 'Void mage helm', emojiHint: '⛑️⚪🔮🛡️✨', wordHint: 'void' },
	{ itemName: "Dharok's helm", emojiHint: '⛑️⚰️💀🛡️💢', wordHint: 'barrows' },
	{ itemName: "Guthan's helm", emojiHint: '⛑️⚰️🩹🛡️💉', wordHint: 'barrows' },
	{ itemName: "Verac's helm", emojiHint: '⛑️⚰️🙏🛡️✨', wordHint: 'barrows' },
	{ itemName: "Torag's helm", emojiHint: '⛑️⚰️🔨🛡️💥', wordHint: 'barrows' },
	{ itemName: "Karil's coif", emojiHint: '⛑️⚰️🏹🛡️🔵', wordHint: 'barrows' },
	{ itemName: "Ahrim's hood", emojiHint: '⛑️⚰️🔮🛡️🟣', wordHint: 'barrows' },
	{ itemName: 'Bandos helmet', emojiHint: '⛑️👺🟤🛡️⚔️', wordHint: 'gwd' },
	{ itemName: 'Armadyl helmet', emojiHint: '⛑️🦅☀️🛡️🏹', wordHint: 'gwd' },
	{ itemName: 'Neitiznot faceguard', emojiHint: '⛑️🧝❄️🛡️💎', wordHint: 'raids' },
	{ itemName: 'Torva full helm', emojiHint: '⛑️🏛️✨🛡️🏆', wordHint: 'nex' },
	{ itemName: "Inquisitor's great helm", emojiHint: '⛑️🔍✨🛡️🏆', wordHint: 'night' },
	{ itemName: 'Justiciar faceguard', emojiHint: '⛑️⚖️🛡️✨🏆', wordHint: 'tob' },
	{ itemName: 'Ancestral hat', emojiHint: '⛑️🏛️🔮🛡️🏆', wordHint: 'raids' },
	{ itemName: 'Crystal helm', emojiHint: '⛑️💎✨🛡️🧝', wordHint: 'elf' },
	{ itemName: 'Masori mask', emojiHint: '⛑️🏛️🏹🛡️🏆', wordHint: 'toa' },
	{ itemName: 'Obsidian helm', emojiHint: '⛑️⚫🌋🛡️🔥', wordHint: 'tzhaar' },
	{ itemName: 'Helm of raedwald', emojiHint: '⛑️👑🛡️✨🔮', wordHint: 'quest' },
	{ itemName: 'Robin hood hat', emojiHint: '🎩🏹🌲🟢🎯', wordHint: 'range' },
	{ itemName: 'Wizard hat', emojiHint: '🎩🔮🌀🟣✨', wordHint: 'magic' },
	{ itemName: 'Mystic hat', emojiHint: '🎩🔮✨🟣🌀', wordHint: 'mystic' },
	{ itemName: "Ahrim's robetop", emojiHint: '👘⚰️🔮🟣💀', wordHint: 'barrows' },
	{ itemName: 'Ahrims robeskirt', emojiHint: '👗⚰️🔮🟣💀', wordHint: 'barrows' },

	// ============================================================
	// PLATEBODIES & CHEST ARMOUR
	// ============================================================
	{ itemName: 'Bronze platebody', emojiHint: '🛡️🟫🔩⛑️🆕', wordHint: 'chest' },
	{ itemName: 'Iron platebody', emojiHint: '🛡️⚫🔩⛑️🆕', wordHint: 'chest' },
	{ itemName: 'Steel platebody', emojiHint: '🛡️⚙️🔩⛑️🆕', wordHint: 'chest' },
	{ itemName: 'Black platebody', emojiHint: '🛡️🖤🔩⛑️🆕', wordHint: 'chest' },
	{ itemName: 'Mithril platebody', emojiHint: '🛡️🔵🔩⛑️🆕', wordHint: 'chest' },
	{ itemName: 'Adamant platebody', emojiHint: '🛡️🟢🔩⛑️🆕', wordHint: 'chest' },
	{ itemName: 'Rune platebody', emojiHint: '🛡️🩵🔩⛑️🆕', wordHint: 'quest' },
	{ itemName: 'Dragon platebody', emojiHint: '🛡️🐉🔩⛑️🏆', wordHint: 'quest' },
	{ itemName: 'Fighter torso', emojiHint: '🛡️💪⚔️⛑️✨', wordHint: 'barb' },
	{ itemName: 'Bandos chestplate', emojiHint: '🛡️👺🟤⛑️⚔️', wordHint: 'gwd' },
	{ itemName: 'Armadyl chestplate', emojiHint: '🛡️🦅☀️⛑️🏹', wordHint: 'gwd' },
	{ itemName: "Dharok's platebody", emojiHint: '🛡️⚰️💀⛑️💢', wordHint: 'barrows' },
	{ itemName: "Guthan's platebody", emojiHint: '🛡️⚰️🩹⛑️💉', wordHint: 'barrows' },
	{ itemName: "Torag's platebody", emojiHint: '🛡️⚰️🔨⛑️💥', wordHint: 'barrows' },
	{ itemName: "Verac's brassard", emojiHint: '🛡️⚰️🙏⛑️✨', wordHint: 'barrows' },
	{ itemName: "Karil's leathertop", emojiHint: '🛡️⚰️🏹⛑️🔵', wordHint: 'barrows' },
	{ itemName: 'Void knight top', emojiHint: '🛡️⚪⚔️⛑️✨', wordHint: 'void' },
	{ itemName: 'Elite void top', emojiHint: '🛡️⚪⭐⛑️✨', wordHint: 'void' },
	{ itemName: 'Torva platebody', emojiHint: '🛡️🏛️✨⛑️🏆', wordHint: 'nex' },
	{ itemName: "Inquisitor's hauberk", emojiHint: '🛡️🔍✨⛑️🏆', wordHint: 'night' },
	{ itemName: 'Justiciar chestguard', emojiHint: '🛡️⚖️⛑️✨🏆', wordHint: 'tob' },
	{ itemName: 'Ancestral robe top', emojiHint: '🛡️🏛️🔮⛑️🏆', wordHint: 'raids' },
	{ itemName: 'Crystal body', emojiHint: '🛡️💎✨⛑️🧝', wordHint: 'elf' },
	{ itemName: 'Masori body', emojiHint: '🛡️🏛️🏹⛑️🏆', wordHint: 'toa' },
	{ itemName: 'Obsidian platebody', emojiHint: '🛡️⚫🌋⛑️🔥', wordHint: 'tzhaar' },
	{ itemName: 'Blessed body', emojiHint: '🛡️✝️🙏⛑️✨', wordHint: 'god' },

	// ============================================================
	// PLATELEGS & SKIRTS
	// ============================================================
	{ itemName: 'Bronze platelegs', emojiHint: '👖🟫🔩🛡️🆕', wordHint: 'legs' },
	{ itemName: 'Iron platelegs', emojiHint: '👖⚫🔩🛡️🆕', wordHint: 'legs' },
	{ itemName: 'Steel platelegs', emojiHint: '👖⚙️🔩🛡️🆕', wordHint: 'legs' },
	{ itemName: 'Black platelegs', emojiHint: '👖🖤🔩🛡️🆕', wordHint: 'legs' },
	{ itemName: 'Mithril platelegs', emojiHint: '👖🔵🔩🛡️🆕', wordHint: 'legs' },
	{ itemName: 'Adamant platelegs', emojiHint: '👖🟢🔩🛡️🆕', wordHint: 'legs' },
	{ itemName: 'Rune platelegs', emojiHint: '👖🩵🔩🛡️🆕', wordHint: 'legs' },
	{ itemName: 'Dragon platelegs', emojiHint: '👖🐉🔩🛡️🏆', wordHint: 'dragon' },
	{ itemName: 'Bandos tassets', emojiHint: '👖👺🟤🛡️⚔️', wordHint: 'gwd' },
	{ itemName: 'Armadyl chainskirt', emojiHint: '👖🦅☀️🛡️🏹', wordHint: 'gwd' },
	{ itemName: "Dharok's platelegs", emojiHint: '👖⚰️💀🛡️💢', wordHint: 'barrows' },
	{ itemName: "Guthan's chainskirt", emojiHint: '👖⚰️🩹🛡️💉', wordHint: 'barrows' },
	{ itemName: "Torag's platelegs", emojiHint: '👖⚰️🔨🛡️💥', wordHint: 'barrows' },
	{ itemName: "Verac's plateskirt", emojiHint: '👖⚰️🙏🛡️✨', wordHint: 'barrows' },
	{ itemName: "Karil's leatherskirt", emojiHint: '👖⚰️🏹🛡️🔵', wordHint: 'barrows' },
	{ itemName: 'Torva platelegs', emojiHint: '👖🏛️✨🛡️🏆', wordHint: 'nex' },
	{ itemName: "Inquisitor's plateskirt", emojiHint: '👖🔍✨🛡️🏆', wordHint: 'night' },
	{ itemName: 'Justiciar legguards', emojiHint: '👖⚖️🛡️✨🏆', wordHint: 'tob' },
	{ itemName: 'Ancestral robe bottom', emojiHint: '👖🏛️🔮🛡️🏆', wordHint: 'raids' },
	{ itemName: 'Crystal legs', emojiHint: '👖💎✨🛡️🧝', wordHint: 'elf' },
	{ itemName: 'Masori chaps', emojiHint: '👖🏛️🏹🛡️🏆', wordHint: 'toa' },
	{ itemName: 'Obsidian platelegs', emojiHint: '👖⚫🌋🛡️🔥', wordHint: 'tzhaar' },

	// ============================================================
	// SHIELDS
	// ============================================================
	{ itemName: 'Bronze sq shield', emojiHint: '🛡️🟫🔩🔲🆕', wordHint: 'block' },
	{ itemName: 'Iron sq shield', emojiHint: '🛡️⚫🔩🔲🆕', wordHint: 'block' },
	{ itemName: 'Steel sq shield', emojiHint: '🛡️⚙️🔩🔲🆕', wordHint: 'block' },
	{ itemName: 'Mithril sq shield', emojiHint: '🛡️🔵🔩🔲🆕', wordHint: 'block' },
	{ itemName: 'Adamant sq shield', emojiHint: '🛡️🟢🔩🔲🆕', wordHint: 'block' },
	{ itemName: 'Rune sq shield', emojiHint: '🛡️🩵🔩🔲🆕', wordHint: 'block' },
	{ itemName: 'Dragon sq shield', emojiHint: '🛡️🐉🔩🔲🏆', wordHint: 'dragon' },
	{ itemName: 'Bronze kiteshield', emojiHint: '🛡️🟫🔩🪁🆕', wordHint: 'block' },
	{ itemName: 'Iron kiteshield', emojiHint: '🛡️⚫🔩🪁🆕', wordHint: 'block' },
	{ itemName: 'Steel kiteshield', emojiHint: '🛡️⚙️🔩🪁🆕', wordHint: 'block' },
	{ itemName: 'Mithril kiteshield', emojiHint: '🛡️🔵🔩🪁🆕', wordHint: 'block' },
	{ itemName: 'Adamant kiteshield', emojiHint: '🛡️🟢🔩🪁🆕', wordHint: 'block' },
	{ itemName: 'Rune kiteshield', emojiHint: '🛡️🩵🔩🪁🆕', wordHint: 'block' },
	{ itemName: 'Dragon kiteshield', emojiHint: '🛡️🐉🔩🪁🏆', wordHint: 'dragon' },
	{ itemName: 'Blessed spirit shield', emojiHint: '🛡️✝️👻🙏✨', wordHint: 'spirit' },
	{ itemName: 'Spectral spirit shield', emojiHint: '🛡️👻✨🙏🔮', wordHint: 'spirit' },
	{ itemName: 'Arcane spirit shield', emojiHint: '🛡️🔮👻✨🙏', wordHint: 'spirit' },
	{ itemName: 'Elysian spirit shield', emojiHint: '🛡️💙👻✨🙏', wordHint: 'spirit' },
	{ itemName: 'Twisted buckler', emojiHint: '🛡️🌀🏹🏆✨', wordHint: 'raids' },
	{ itemName: 'Avernic defender', emojiHint: '🛡️⚔️🔴✨🏆', wordHint: 'tob' },
	{ itemName: 'Crystal shield', emojiHint: '🛡️💎✨🧝🔵', wordHint: 'elf' },
	{ itemName: 'Dragonfire shield', emojiHint: '🛡️🐉🔥✨💎', wordHint: 'dragon' },
	{ itemName: 'Dragonfire ward', emojiHint: '🛡️🐉🔥🏹✨', wordHint: 'dragon' },
	{ itemName: 'Anti-dragon shield', emojiHint: '🛡️🐉🔥🚫⛑️', wordHint: 'dragon' },
	{ itemName: 'Toktz-ket-xil', emojiHint: '🛡️🌋⚫🔥✨', wordHint: 'tzhaar' },
	{ itemName: "Elidinis' ward", emojiHint: '🛡️🏛️🔮✨🏆', wordHint: 'toa' },
	{ itemName: 'Malediction ward', emojiHint: '🛡️☠️🔮✨🌑', wordHint: 'wilds' },
	{ itemName: 'Odium ward', emojiHint: '🛡️😡🏹✨🌑', wordHint: 'wilds' },

	// ============================================================
	// BOOTS & GLOVES
	// ============================================================
	{ itemName: 'Bronze boots', emojiHint: '👢🟫🔩🛡️🆕', wordHint: 'feet' },
	{ itemName: 'Iron boots', emojiHint: '👢⚫🔩🛡️🆕', wordHint: 'feet' },
	{ itemName: 'Steel boots', emojiHint: '👢⚙️🔩🛡️🆕', wordHint: 'feet' },
	{ itemName: 'Black boots', emojiHint: '👢🖤🔩🛡️🆕', wordHint: 'feet' },
	{ itemName: 'Mithril boots', emojiHint: '👢🔵🔩🛡️🆕', wordHint: 'feet' },
	{ itemName: 'Adamant boots', emojiHint: '👢🟢🔩🛡️🆕', wordHint: 'feet' },
	{ itemName: 'Rune boots', emojiHint: '👢🩵🔩🛡️🆕', wordHint: 'feet' },
	{ itemName: 'Dragon boots', emojiHint: '👢🐉🔩🛡️🏆', wordHint: 'dragon' },
	{ itemName: 'Bandos boots', emojiHint: '👢👺🟤🛡️⚔️', wordHint: 'gwd' },
	{ itemName: 'Primordial boots', emojiHint: '👢🐉🔥✨🏆', wordHint: 'dragon' },
	{ itemName: 'Pegasian boots', emojiHint: '👢🐉🏹✨🏆', wordHint: 'dragon' },
	{ itemName: 'Eternal boots', emojiHint: '👢🐉🔮✨🏆', wordHint: 'dragon' },
	{ itemName: 'Ranger boots', emojiHint: '👢🏹🌲🟢🎯', wordHint: 'range' },
	{ itemName: 'Infinity boots', emojiHint: '👢🔮∞✨🟣', wordHint: 'magic' },
	{ itemName: 'Guardian boots', emojiHint: '👢🛡️⚙️✨🔵', wordHint: 'kourend' },
	{ itemName: 'Snakeskin boots', emojiHint: '👢🐍🌿🟤🎯', wordHint: 'range' },
	{ itemName: 'Brine sabre', emojiHint: '⚔️🌊🧂🟡✨', wordHint: 'slash' },
	{ itemName: 'Bronze gloves', emojiHint: '🤜🟫🔩🛡️🆕', wordHint: 'hands' },
	{ itemName: 'Iron gloves', emojiHint: '🤜⚫🔩🛡️🆕', wordHint: 'hands' },
	{ itemName: 'Steel gloves', emojiHint: '🤜⚙️🔩🛡️🆕', wordHint: 'hands' },
	{ itemName: 'Black gloves', emojiHint: '🤜🖤🔩🛡️🆕', wordHint: 'hands' },
	{ itemName: 'Mithril gloves', emojiHint: '🤜🔵🔩🛡️🆕', wordHint: 'hands' },
	{ itemName: 'Adamant gloves', emojiHint: '🤜🟢🔩🛡️🆕', wordHint: 'hands' },
	{ itemName: 'Rune gloves', emojiHint: '🤜🩵🔩🛡️🆕', wordHint: 'hands' },
	{ itemName: 'Dragon gloves', emojiHint: '🤜🐉🔩🛡️🏆', wordHint: 'hands' },
	{ itemName: 'Barrows gloves', emojiHint: '🤜⚰️💀🛡️✨', wordHint: 'quest' },
	{ itemName: 'Void knight gloves', emojiHint: '🤜⚪⚔️🛡️✨', wordHint: 'void' },
	{ itemName: 'Graceful gloves', emojiHint: '🤜🏃✨🌟💨', wordHint: 'grace' },
	{ itemName: 'Ferocious gloves', emojiHint: '🤜🦷💀⚔️✨', wordHint: 'dragon' },
	{ itemName: 'Tormented bracelet', emojiHint: '🤜😫✨🔮💎', wordHint: 'magic' },
	{ itemName: 'Zaryte vambraces', emojiHint: '🤜🏛️🏹✨🏆', wordHint: 'nex' },

	// ============================================================
	// CAPES
	// ============================================================
	{ itemName: 'Cape of accomplishment', emojiHint: '🏅🎭✨🎉👑', wordHint: 'skill' },
	{ itemName: 'Fire cape', emojiHint: '🔥🌋🏆🎭⚔️', wordHint: 'inferno' },
	{ itemName: 'Infernal cape', emojiHint: '🌋🔥🏆🎭⚔️', wordHint: 'inferno' },
	{ itemName: 'Saradomin cape', emojiHint: '☀️🏅🙏✨🎭', wordHint: 'god' },
	{ itemName: 'Zamorak cape', emojiHint: '🔴🏅😈✨🎭', wordHint: 'god' },
	{ itemName: 'Guthix cape', emojiHint: '⚖️🏅🌿✨🎭', wordHint: 'god' },
	{ itemName: "Ava's assembler", emojiHint: '🎭🏹✨🔵🤖', wordHint: 'ava' },
	{ itemName: "Ava's accumulator", emojiHint: '🎭🏹✨🔵🤖', wordHint: 'ava' },
	{ itemName: "Ava's attractor", emojiHint: '🎭🏹🔵🤖🆕', wordHint: 'ava' },
	{ itemName: 'Max cape', emojiHint: '👑🏅🏆✨🎭', wordHint: 'max' },
	{ itemName: 'Mythical cape', emojiHint: '🐉🏅✨🎭🏆', wordHint: 'quest' },
	{ itemName: 'Ardougne cloak', emojiHint: '🎭🏙️🧥🌿✨', wordHint: 'diary' },
	{ itemName: 'Graceful cape', emojiHint: '🎭🏃✨🌟💨', wordHint: 'grace' },
	{ itemName: 'Obsidian cape', emojiHint: '🎭⚫🌋🔥✨', wordHint: 'tzhaar' },
	{ itemName: 'Soul bearer', emojiHint: '👻🎭🔮✨🕳️', wordHint: 'soul' },
	{ itemName: 'Ranging cape', emojiHint: '🎭🏹✨🌟🏆', wordHint: 'skill' },
	{ itemName: 'Magic cape', emojiHint: '🎭🔮✨🌟🏆', wordHint: 'skill' },
	{ itemName: 'Prayer cape', emojiHint: '🎭🙏✨🌟🏆', wordHint: 'skill' },
	{ itemName: 'Slayer cape', emojiHint: '🎭💀✨🌟🏆', wordHint: 'skill' },
	{ itemName: 'Quest point cape', emojiHint: '🎭📜✨🌟🏆', wordHint: 'quest' },

	// ============================================================
	// AMULETS & NECKLACES
	// ============================================================
	{ itemName: 'Amulet of strength', emojiHint: '📿💪🟠✨⚔️', wordHint: 'str' },
	{ itemName: 'Amulet of defence', emojiHint: '📿🛡️🟠✨⚔️', wordHint: 'block' },
	{ itemName: 'Amulet of magic', emojiHint: '📿🔮🟣✨🔵', wordHint: 'magic' },
	{ itemName: 'Amulet of power', emojiHint: '📿💥🟠✨⚔️', wordHint: 'power' },
	{ itemName: 'Amulet of glory', emojiHint: '📿✨💎🟠🏆', wordHint: 'glory' },
	{ itemName: 'Amulet of torture', emojiHint: '📿😖💎⚔️🏆', wordHint: 'zenyte' },
	{ itemName: 'Amulet of anguish', emojiHint: '📿😟💎🏹🏆', wordHint: 'zenyte' },
	{ itemName: 'Occult necklace', emojiHint: '📿🔮☠️✨🏆', wordHint: 'magic' },
	{ itemName: 'Amulet of fury', emojiHint: '📿😡💎🟠🏆', wordHint: 'onyx' },
	{ itemName: 'Necklace of anguish', emojiHint: '📿😟💎🏹🏆', wordHint: 'zenyte' },
	{ itemName: 'Berserker necklace', emojiHint: '📿💢⚫🌋⚔️', wordHint: 'obsidian' },
	{ itemName: 'Amulet of eternal glory', emojiHint: '📿✨💎♾️🏆', wordHint: 'glory' },
	{ itemName: 'Dragonbone necklace', emojiHint: '📿🐉🦴✨🙏', wordHint: 'pray' },
	{ itemName: 'Holy necklace', emojiHint: '📿✝️✨🙏🟡', wordHint: 'holy' },
	{ itemName: 'Salve amulet', emojiHint: '📿💀✨🧟🔵', wordHint: 'undead' },
	{ itemName: 'Salve amulet (e)', emojiHint: '📿💀✨🧟⭐', wordHint: 'undead' },
	{ itemName: 'Salve amulet (ei)', emojiHint: '📿💀✨🧟💎', wordHint: 'undead' },

	// ============================================================
	// RINGS
	// ============================================================
	{ itemName: 'Ring of recoil', emojiHint: '💍🔄💥⚡🔴', wordHint: 'recoil' },
	{ itemName: 'Ring of dueling', emojiHint: '💍⚔️🏟️⚡🎯', wordHint: 'duel' },
	{ itemName: 'Ring of life', emojiHint: '💍❤️🛡️⚡✨', wordHint: 'life' },
	{ itemName: 'Ring of wealth', emojiHint: '💍💰✨⚡🟡', wordHint: 'wealth' },
	{ itemName: 'Ring of suffering', emojiHint: '💍😫💎✨🏆', wordHint: 'zenyte' },
	{ itemName: 'Berserker ring', emojiHint: '💍💢⚔️✨🏆', wordHint: 'slayer' },
	{ itemName: 'Berserker ring (i)', emojiHint: '💍💢⚔️✨⭐', wordHint: 'imbue' },
	{ itemName: 'Archer ring', emojiHint: '💍🏹✨🎯🏆', wordHint: 'slayer' },
	{ itemName: 'Archer ring (i)', emojiHint: '💍🏹✨🎯⭐', wordHint: 'imbue' },
	{ itemName: 'Seers ring', emojiHint: '💍🔮✨👁️🏆', wordHint: 'slayer' },
	{ itemName: 'Seers ring (i)', emojiHint: '💍🔮✨👁️⭐', wordHint: 'imbue' },
	{ itemName: 'Warrior ring', emojiHint: '💍⚔️✨💪🏆', wordHint: 'slayer' },
	{ itemName: 'Warrior ring (i)', emojiHint: '💍⚔️✨💪⭐', wordHint: 'imbue' },
	{ itemName: 'Ring of the gods', emojiHint: '💍🙏✨👑🏆', wordHint: 'wilds' },
	{ itemName: 'Treasonous ring', emojiHint: '💍🗡️✨🌑🏆', wordHint: 'wilds' },
	{ itemName: 'Tyrannical ring', emojiHint: '💍👑✨🌑🏆', wordHint: 'wilds' },
	{ itemName: 'Lightbearer', emojiHint: '💍💡✨🔦🏆', wordHint: 'raids' },

	// ============================================================
	// GRACEFUL SET
	// ============================================================
	{ itemName: 'Graceful hood', emojiHint: '⛑️🏃✨🌟💨', wordHint: 'grace' },
	{ itemName: 'Graceful top', emojiHint: '🛡️🏃✨🌟💨', wordHint: 'grace' },
	{ itemName: 'Graceful legs', emojiHint: '👖🏃✨🌟💨', wordHint: 'grace' },
	{ itemName: 'Graceful boots', emojiHint: '👢🏃✨🌟💨', wordHint: 'grace' },
	{ itemName: 'Graceful gloves', emojiHint: '🤜🏃✨🌟💨', wordHint: 'grace' },
	{ itemName: 'Graceful cape', emojiHint: '🎭🏃✨🌟💨', wordHint: 'grace' },

	// ============================================================
	// SKILLING TOOLS
	// ============================================================
	{ itemName: 'Tinderbox', emojiHint: '🔥💡🪵🕯️🔦', wordHint: 'fire' },
	{ itemName: 'Knife', emojiHint: '🔪🪵🌿🍎🔧', wordHint: 'fletch' },
	{ itemName: 'Chisel', emojiHint: '⛏️💎🔧🪨✂️', wordHint: 'craft' },
	{ itemName: 'Hammer', emojiHint: '🔨🔩⚒️🏭🔧', wordHint: 'smith' },
	{ itemName: 'Saw', emojiHint: '🪚🪵🏠🔧🌲', wordHint: 'build' },
	{ itemName: 'Needle', emojiHint: '🪡🧵💍✂️🔧', wordHint: 'craft' },
	{ itemName: 'Thread', emojiHint: '🧵🪡💍✂️🔧', wordHint: 'craft' },
	{ itemName: 'Shears', emojiHint: '✂️🐑🌿🧵🔧', wordHint: 'flax' },
	{ itemName: 'Bucket', emojiHint: '🪣💧🌿🐄🔧', wordHint: 'water' },
	{ itemName: 'Pot', emojiHint: '🪣🌾🌿🍞🔧', wordHint: 'flour' },
	{ itemName: 'Jug', emojiHint: '🫙💧🍷🌊🔧', wordHint: 'water' },
	{ itemName: 'Pestle and mortar', emojiHint: '🧪🌿🔧⚗️💊', wordHint: 'grind' },
	{ itemName: 'Vial', emojiHint: '🧪💧🌿🔧⚗️', wordHint: 'potion' },
	{ itemName: 'Vial of water', emojiHint: '🧪💧✨🌿⚗️', wordHint: 'potion' },
	{ itemName: 'Knife', emojiHint: '🔪🍎🧵🪵🔧', wordHint: 'fletch' },
	{ itemName: 'Fishing rod', emojiHint: '🎣🪝🌊🐟🔧', wordHint: 'bait' },
	{ itemName: 'Fly fishing rod', emojiHint: '🎣🪰🌊🐟🔧', wordHint: 'flies' },
	{ itemName: 'Lobster pot', emojiHint: '🦞🪤🌊🎣🔧', wordHint: 'pot' },
	{ itemName: 'Big fishing net', emojiHint: '🕸️🌊🐟🎣🔧', wordHint: 'bignet' },
	{ itemName: 'Small fishing net', emojiHint: '🕸️🌊🦐🎣🔧', wordHint: 'net' },
	{ itemName: 'Harpoon', emojiHint: '🔱🌊🦈🎣🔧', wordHint: 'stab' },
	{ itemName: 'Barbarian rod', emojiHint: '🎣🏔️🌊🐟🔧', wordHint: 'barb' },
	{ itemName: 'Karambwan vessel', emojiHint: '🐙🏝️🌊🎣🔧', wordHint: 'vessel' },
	{ itemName: 'Sandworms', emojiHint: '🪱🏝️🌊🎣🔧', wordHint: 'bait' },
	{ itemName: 'Rake', emojiHint: '🌱🌾🌿🚜🔧', wordHint: 'farm' },
	{ itemName: 'Spade', emojiHint: '⛏️🌱🌿🚜🔧', wordHint: 'dig' },
	{ itemName: 'Seed dibber', emojiHint: '🌱🌾🌿🚜🔧', wordHint: 'plant' },
	{ itemName: 'Watering can', emojiHint: '💧🌱🌿🚜🔧', wordHint: 'water' },
	{ itemName: 'Plant cure', emojiHint: '💊🌱🌿🚜🔧', wordHint: 'cure' },
	{ itemName: 'Compost', emojiHint: '🌿🌱🟤🚜🔧', wordHint: 'farm' },
	{ itemName: 'Supercompost', emojiHint: '🌿🌱🟢🚜🔧', wordHint: 'farm' },
	{ itemName: 'Ultracompost', emojiHint: '🌿🌱💜🚜🔧', wordHint: 'farm' },
	{ itemName: 'Trowel', emojiHint: '⛏️🌱🌿🚜🔧', wordHint: 'farm' },
	{ itemName: 'Magic secateurs', emojiHint: '✂️🌿✨🌱🚜', wordHint: 'farm' },
	{ itemName: 'Glassblowing pipe', emojiHint: '🔧🫧💨🟦✨', wordHint: 'craft' },
	{ itemName: 'Molten glass', emojiHint: '🔥🟦💨✨🔧', wordHint: 'craft' },
	{ itemName: 'Flax', emojiHint: '🌾🌿🧵💙🔧', wordHint: 'spin' },
	{ itemName: 'Ball of wool', emojiHint: '🧶🐑🌿✨🔧', wordHint: 'craft' },
	{ itemName: 'Spinning wheel', emojiHint: '🌀🧵🐑🌿🔧', wordHint: 'spin' },
	{ itemName: 'Soft clay', emojiHint: '🟫🌿💧🔧✨', wordHint: 'craft' },
	{ itemName: 'Unfired bowl', emojiHint: '🟫🌿🔥🔧✨', wordHint: 'craft' },
	{ itemName: 'Crayfish cage', emojiHint: '🦞🪤💧🎣🔧', wordHint: 'fish' },
	{ itemName: 'Impling jar', emojiHint: '🫙🦋✨🌿🔧', wordHint: 'hunter' },

	// ============================================================
	// JEWELLERY (UNCUT GEMS)
	// ============================================================
	{ itemName: 'Uncut sapphire', emojiHint: '💎🔵🪨✨🔧', wordHint: 'gem' },
	{ itemName: 'Uncut emerald', emojiHint: '💎🟢🪨✨🔧', wordHint: 'gem' },
	{ itemName: 'Uncut ruby', emojiHint: '💎🔴🪨✨🔧', wordHint: 'gem' },
	{ itemName: 'Uncut diamond', emojiHint: '💎💠🪨✨🔧', wordHint: 'gem' },
	{ itemName: 'Uncut dragonstone', emojiHint: '💎🐉🪨✨🔧', wordHint: 'gem' },
	{ itemName: 'Uncut onyx', emojiHint: '💎⚫🪨✨🔧', wordHint: 'gem' },
	{ itemName: 'Uncut zenyte', emojiHint: '💎🟣🪨✨🔧', wordHint: 'gem' },
	{ itemName: 'Sapphire', emojiHint: '💎🔵✨🔧💍', wordHint: 'blue' },
	{ itemName: 'Emerald', emojiHint: '💎🟢✨🔧💍', wordHint: 'green' },
	{ itemName: 'Ruby', emojiHint: '💎🔴✨🔧💍', wordHint: 'red' },
	{ itemName: 'Diamond', emojiHint: '💎💠✨🔧💍', wordHint: 'clear' },
	{ itemName: 'Dragonstone', emojiHint: '💎🐉✨🔧💍', wordHint: 'dragon' },
	{ itemName: 'Onyx', emojiHint: '💎⚫✨🔧💍', wordHint: 'black' },
	{ itemName: 'Zenyte', emojiHint: '💎🟣✨🔧💍', wordHint: 'monkey' },
	{ itemName: 'Opal', emojiHint: '💎🌈✨🔧💍', wordHint: 'color' },
	{ itemName: 'Red topaz', emojiHint: '💎🔴🟠✨🔧', wordHint: 'topaz' },
	{ itemName: 'Jade', emojiHint: '💎🟢✨🔧🌿', wordHint: 'jade' },

	// ============================================================
	// PRAYER & BONES
	// ============================================================
	{ itemName: 'Bones', emojiHint: '🦴🙏💀✨⬆️', wordHint: 'pray' },
	{ itemName: 'Big bones', emojiHint: '🦴💪🙏💀⬆️', wordHint: 'pray' },
	{ itemName: 'Dragon bones', emojiHint: '🦴🐉🙏✨⬆️', wordHint: 'pray' },
	{ itemName: 'Superior dragon bones', emojiHint: '🦴🐉🏆🙏✨', wordHint: 'pray' },
	{ itemName: 'Wyvern bones', emojiHint: '🦴🦕🙏✨⬆️', wordHint: 'pray' },
	{ itemName: 'Dagannoth bones', emojiHint: '🦴🦈🙏✨⬆️', wordHint: 'pray' },
	{ itemName: 'Lava dragon bones', emojiHint: '🦴🌋🙏🔥⬆️', wordHint: 'pray' },
	{ itemName: 'Babydragon bones', emojiHint: '🦴🐣🙏✨⬆️', wordHint: 'pray' },
	{ itemName: 'Ourg bones', emojiHint: '🦴👹🙏✨⬆️', wordHint: 'pray' },
	{ itemName: 'Jogre bones', emojiHint: '🦴🧟🙏✨⬆️', wordHint: 'pray' },
	{ itemName: 'Zogre bones', emojiHint: '🦴🧟🙏✨⬆️', wordHint: 'pray' },
	{ itemName: 'Prayer potion', emojiHint: '🙏🧪💊🟡⬆️', wordHint: 'pray' },
	{ itemName: 'Ensouled head', emojiHint: '💀👻🔮🙏✨', wordHint: 'pray' },
	{ itemName: 'Ashes', emojiHint: '🔥⚫💨🙏🪣', wordHint: 'burn' },
	{ itemName: 'Infernal ashes', emojiHint: '🔥⚫🌋🙏💨', wordHint: 'infernal' },
	{ itemName: 'Nihil dust', emojiHint: '💀🏛️✨💨🔮', wordHint: 'nex' },
	{ itemName: 'Holy book', emojiHint: '📖✝️🙏✨🟡', wordHint: 'holy' },
	{ itemName: 'Unholy book', emojiHint: '📖😈🙏✨🔴', wordHint: 'unholy' },
	{ itemName: 'Book of balance', emojiHint: '📖⚖️🙏✨🟢', wordHint: 'guthix' },
	{ itemName: 'Book of war', emojiHint: '📖⚔️🙏✨🟤', wordHint: 'bandos' },
	{ itemName: 'Book of law', emojiHint: '📖⚖️🙏✨🦅', wordHint: 'armadyl' },
	{ itemName: 'Book of darkness', emojiHint: '📖🌑🙏✨🔵', wordHint: 'ancient' },
	{ itemName: 'God page', emojiHint: '📄✝️🙏✨🌟', wordHint: 'clue' },

	// ============================================================
	// TELEPORT TABLETS & TELEPORTS
	// ============================================================
	{ itemName: 'Lumbridge teleport', emojiHint: '🏰🔮💨✨⚡', wordHint: 'tele' },
	{ itemName: 'Falador teleport', emojiHint: '🏰🔮💨🔵⚡', wordHint: 'tele' },
	{ itemName: 'Varrock teleport', emojiHint: '🏰🔮💨🔴⚡', wordHint: 'tele' },
	{ itemName: 'Camelot teleport', emojiHint: '🏰🔮💨🟡⚡', wordHint: 'tele' },
	{ itemName: 'Ardougne teleport', emojiHint: '🏰🔮💨🏙️⚡', wordHint: 'tele' },
	{ itemName: 'Watchtower teleport', emojiHint: '🏰🔮💨🗼⚡', wordHint: 'tele' },
	{ itemName: 'Trollheim teleport', emojiHint: '🏰🔮💨🏔️⚡', wordHint: 'tele' },
	{ itemName: 'House teleport', emojiHint: '🏠🔮💨🔵⚡', wordHint: 'tele' },
	{ itemName: 'Amulet of glory', emojiHint: '📿✨💎🟠⚡', wordHint: 'tele' },
	{ itemName: 'Games necklace', emojiHint: '📿🎮🔵✨⚡', wordHint: 'tele' },
	{ itemName: 'Combat bracelet', emojiHint: '📿⚔️🟠✨⚡', wordHint: 'tele' },
	{ itemName: 'Skills necklace', emojiHint: '📿🌟🟠✨⚡', wordHint: 'tele' },
	{ itemName: 'Necklace of passage', emojiHint: '📿🚪🟠✨⚡', wordHint: 'tele' },
	{ itemName: 'Ring of dueling', emojiHint: '💍⚔️🔵✨⚡', wordHint: 'tele' },
	{ itemName: 'Slayer ring', emojiHint: '💍💀🔵✨⚡', wordHint: 'tele' },
	{ itemName: "Explorer's ring", emojiHint: '💍🧭🔵✨⚡', wordHint: 'diary' },

	// ============================================================
	// CLUE SCROLL REWARDS
	// ============================================================
	{ itemName: 'Gilded full helm', emojiHint: '⛑️🟡✨📜🏆', wordHint: 'clue' },
	{ itemName: 'Gilded platebody', emojiHint: '🛡️🟡✨📜🏆', wordHint: 'clue' },
	{ itemName: 'Gilded platelegs', emojiHint: '👖🟡✨📜🏆', wordHint: 'clue' },
	{ itemName: 'Gilded plateskirt', emojiHint: '👗🟡✨📜🏆', wordHint: 'clue' },
	{ itemName: 'Gilded boots', emojiHint: '👢🟡✨📜🏆', wordHint: 'clue' },
	{ itemName: 'Gilded med helm', emojiHint: '⛑️🟡✨📜🏆', wordHint: 'clue' },
	{ itemName: 'Gilded sq shield', emojiHint: '🛡️🟡✨📜🏆', wordHint: 'clue' },
	{ itemName: 'Gilded kiteshield', emojiHint: '🛡️🟡✨📜🏆', wordHint: 'clue' },
	{ itemName: 'Ranger hat', emojiHint: '🎩🏹🌲✨📜', wordHint: 'clue' },
	{ itemName: 'Ranger gloves', emojiHint: '🤜🏹🌲✨📜', wordHint: 'clue' },
	{ itemName: 'Robin hood hat', emojiHint: '🎩🏹🌲🟢📜', wordHint: 'clue' },
	{ itemName: 'Wizard hat', emojiHint: '🎩🔮🌀🟣📜', wordHint: 'clue' },
	{ itemName: '3rd age full helmet', emojiHint: '⛑️🏛️✨📜🏆', wordHint: 'rare' },
	{ itemName: '3rd age platebody', emojiHint: '🛡️🏛️✨📜🏆', wordHint: 'rare' },
	{ itemName: '3rd age platelegs', emojiHint: '👖🏛️✨📜🏆', wordHint: 'rare' },
	{ itemName: '3rd age kiteshield', emojiHint: '🛡️🏛️✨📜🏆', wordHint: 'rare' },
	{ itemName: '3rd age bow', emojiHint: '🏹🏛️✨📜🏆', wordHint: 'rare' },
	{ itemName: '3rd age wand', emojiHint: '🪄🏛️✨📜🏆', wordHint: 'rare' },
	{ itemName: '3rd age cloak', emojiHint: '🎭🏛️✨📜🏆', wordHint: 'rare' },
	{ itemName: '3rd age longsword', emojiHint: '⚔️🏛️✨📜🏆', wordHint: 'rare' },
	{ itemName: 'Clue scroll (easy)', emojiHint: '📜🗺️🔎🟢🏆', wordHint: 'clue' },
	{ itemName: 'Clue scroll (medium)', emojiHint: '📜🗺️🔎🟡🏆', wordHint: 'clue' },
	{ itemName: 'Clue scroll (hard)', emojiHint: '📜🗺️🔎🔴🏆', wordHint: 'clue' },
	{ itemName: 'Clue scroll (elite)', emojiHint: '📜🗺️🔎💜🏆', wordHint: 'clue' },
	{ itemName: 'Clue scroll (master)', emojiHint: '📜🗺️🔎👑🏆', wordHint: 'clue' },
	{ itemName: 'Reward casket (easy)', emojiHint: '📦🟢✨🏆🎉', wordHint: 'clue' },
	{ itemName: 'Reward casket (hard)', emojiHint: '📦🔴✨🏆🎉', wordHint: 'clue' },
	{ itemName: 'Reward casket (elite)', emojiHint: '📦💜✨🏆🎉', wordHint: 'clue' },

	// ============================================================
	// QUEST ITEMS
	// ============================================================
	{ itemName: 'Shantay pass', emojiHint: '📜🏜️🔑🚪✨', wordHint: 'quest' },
	{ itemName: 'Ghostspeak amulet', emojiHint: '📿👻🗣️✨🙏', wordHint: 'ghost' },
	{ itemName: 'Dramen staff', emojiHint: '🪄🌲✨🧝🏝️', wordHint: 'fairy' },
	{ itemName: 'Lunar staff', emojiHint: '🪄🌙✨🧙✨', wordHint: 'lunar' },
	{ itemName: 'Seal of passage', emojiHint: '📜🚪🔑✨🧙', wordHint: 'lunar' },
	{ itemName: 'Lumbridge guide', emojiHint: '📖🏰✨🆕🗺️', wordHint: 'guide' },
	{ itemName: 'Goblin mail', emojiHint: '🛡️👺🟠📜🔧', wordHint: 'quest' },
	{ itemName: 'Cat', emojiHint: '🐱🏠✨🐭🎁', wordHint: 'gertrude' },
	{ itemName: 'Kitten', emojiHint: '🐱🏠🆕🐭🎁', wordHint: 'gertrude' },
	{ itemName: 'Wily cat', emojiHint: '🐱🦊✨🐭🎁', wordHint: 'sneaky' },
	{ itemName: 'Overgrown cat', emojiHint: '🐱😴✨🐭🎁', wordHint: 'old' },
	{ itemName: 'Pet kitten', emojiHint: '🐱❤️✨🐭🎁', wordHint: 'pet' },
	{ itemName: 'Dragon key piece', emojiHint: '🔑🐉✨🏰🔓', wordHint: 'quest' },
	{ itemName: 'Crystal saw', emojiHint: '🪚💎✨🧝🏠', wordHint: 'elf' },
	{ itemName: 'Monkey greegree', emojiHint: '🐒✨🗡️🏝️🔮', wordHint: 'monkey' },
	{ itemName: 'Ape atoll teleport', emojiHint: '🐒🏝️🔮💨⚡', wordHint: 'tele' },
	{ itemName: "Pharaoh's sceptre", emojiHint: '🏛️⚡🔮🧙✨', wordHint: 'pyramid' },
	{ itemName: 'Blighted supply sack', emojiHint: '💀🎒🌑✨⚔️', wordHint: 'wilds' },

	// ============================================================
	// BOSS DROPS & UNIQUE ITEMS
	// ============================================================
	{ itemName: 'Bandos tassets', emojiHint: '👺👖🟤⚔️🏆', wordHint: 'gwd' },
	{ itemName: 'Bandos chestplate', emojiHint: '👺🛡️🟤⚔️🏆', wordHint: 'gwd' },
	{ itemName: 'Armadyl helmet', emojiHint: '🦅⛑️☀️🏹🏆', wordHint: 'gwd' },
	{ itemName: 'Armadyl chestplate', emojiHint: '🦅🛡️☀️🏹🏆', wordHint: 'gwd' },
	{ itemName: 'Armadyl chainskirt', emojiHint: '🦅👖☀️🏹🏆', wordHint: 'gwd' },
	{ itemName: 'Zamorakian spear', emojiHint: '🔴🗡️😈🏆⚔️', wordHint: 'gwd' },
	{ itemName: 'Steam battlestaff', emojiHint: '♨️🪄⚔️🔮🏆', wordHint: 'gwd' },
	{ itemName: 'Saradomin sword', emojiHint: '☀️⚔️🙏🏆✨', wordHint: 'gwd' },
	{ itemName: "Saradomin's light", emojiHint: '☀️💡🙏✨🏆', wordHint: 'gwd' },
	{ itemName: 'Pet saradomin owl', emojiHint: '🦉☀️🙏✨❤️', wordHint: 'pet' },
	{ itemName: 'Pet general graardor', emojiHint: '👺✨❤️🏆🟤', wordHint: 'pet' },
	{ itemName: 'Pet zilyana', emojiHint: '☀️👸✨❤️🏆', wordHint: 'pet' },
	{ itemName: "Pet kree'arra", emojiHint: '🦅✨❤️🏆🏹', wordHint: 'pet' },
	{ itemName: "Pet k'ril tsutsaroth", emojiHint: '🔴😈✨❤️🏆', wordHint: 'pet' },
	{ itemName: 'Tanzanite fang', emojiHint: '🐍💙✨🗡️🔵', wordHint: 'zulrah' },
	{ itemName: 'Magic fang', emojiHint: '🐍🔮✨🗡️🟢', wordHint: 'zulrah' },
	{ itemName: 'Serpentine visage', emojiHint: '🐍👺✨🛡️🟢', wordHint: 'zulrah' },
	{ itemName: 'Uncut onyx', emojiHint: '💎⚫✨🐍🏆', wordHint: 'zulrah' },
	{ itemName: "Zulrah's scales", emojiHint: '🐍🐟✨💎🏆', wordHint: 'zulrah' },
	{ itemName: 'Pet snakeling', emojiHint: '🐍🐣✨❤️🏆', wordHint: 'pet' },
	{ itemName: "Vorkath's head", emojiHint: '🐉💀⚗️✨🏆', wordHint: 'undead' },
	{ itemName: 'Dragonbone necklace', emojiHint: '📿🐉🦴✨🙏', wordHint: 'pray' },
	{ itemName: 'Skeletal visage', emojiHint: '💀🐉🛡️✨🏆', wordHint: 'dragon' },
	{ itemName: 'Draconic visage', emojiHint: '🐉🛡️💎✨🏆', wordHint: 'dragon' },
	{ itemName: 'Jar of stone', emojiHint: '🫙🪨✨🏆🐛', wordHint: 'wyrm' },
	{ itemName: 'Jar of souls', emojiHint: '🫙👻✨🏆💀', wordHint: 'cerb' },
	{ itemName: 'Primordial crystal', emojiHint: '💎🔥🐉✨🏆', wordHint: 'cerb' },
	{ itemName: 'Pegasian crystal', emojiHint: '💎🏹🐉✨🏆', wordHint: 'cerb' },
	{ itemName: 'Eternal crystal', emojiHint: '💎🔮🐉✨🏆', wordHint: 'cerb' },
	{ itemName: 'Smouldering stone', emojiHint: '🪨🔥✨🏆⚒️', wordHint: 'cerb' },
	{ itemName: 'Smoke battlestaff', emojiHint: '🌫️🪄⚔️🔮🏆', wordHint: 'slayer' },
	{ itemName: 'Occult necklace', emojiHint: '📿☠️🔮✨🏆', wordHint: 'slayer' },
	{ itemName: 'Abyssal whip', emojiHint: '🕳️🪱⚔️✨🏆', wordHint: 'slayer' },
	{ itemName: 'Abyssal dagger', emojiHint: '🕳️🗡️💀✨🏆', wordHint: 'slayer' },
	{ itemName: 'Abyssal bludgeon', emojiHint: '🕳️⚒️💀✨🏆', wordHint: 'slayer' },
	{ itemName: 'Abyssal orphan', emojiHint: '🕳️🐣✨❤️🏆', wordHint: 'pet' },
	{ itemName: 'Jar of darkness', emojiHint: '🫙🌑✨🏆💀', wordHint: 'slayer' },
	{ itemName: "Hydra's claw", emojiHint: '🦎🔪✨🏆⚔️', wordHint: 'hydra' },
	{ itemName: 'Hydra leather', emojiHint: '🦎🎽✨🏆🛡️', wordHint: 'hydra' },
	{ itemName: "Hydra's eye", emojiHint: '🦎👁️✨🏆💊', wordHint: 'hydra' },
	{ itemName: "Hydra's fang", emojiHint: '🦎🦷✨🏆💊', wordHint: 'hydra' },
	{ itemName: "Hydra's heart", emojiHint: '🦎❤️✨🏆💊', wordHint: 'hydra' },
	{ itemName: 'Brimstone ring', emojiHint: '💍🌋✨🏆🔮', wordHint: 'hydra' },
	{ itemName: 'Pet rift guardian', emojiHint: '🕳️🐣✨❤️🏆', wordHint: 'pet' },
	{ itemName: 'Pet dagannoth prime', emojiHint: '🦈🐣✨❤️🏆', wordHint: 'pet' },
	{ itemName: 'Pet dagannoth supreme', emojiHint: '🦈🐣✨❤️🏆', wordHint: 'pet' },
	{ itemName: 'Pet dagannoth rex', emojiHint: '🦈👑✨❤️🏆', wordHint: 'pet' },
	{ itemName: 'Berserker ring', emojiHint: '💍💢⚔️✨🏆', wordHint: 'dagg' },
	{ itemName: 'Seers ring', emojiHint: '💍🔮✨👁️🏆', wordHint: 'dagg' },
	{ itemName: 'Archer ring', emojiHint: '💍🏹✨🎯🏆', wordHint: 'dagg' },
	{ itemName: 'Warrior ring', emojiHint: '💍⚔️✨💪🏆', wordHint: 'dagg' },
	{ itemName: 'Berserker necklace', emojiHint: '📿💢⚫🌋⚔️', wordHint: 'dagg' },
	{ itemName: 'Mud battlestaff', emojiHint: '🟫🪄⚔️🔮🏆', wordHint: 'dagg' },
	{ itemName: 'Seercull', emojiHint: '🏹🎯✨💀🏆', wordHint: 'dagg' },
	{ itemName: 'Dragon axe', emojiHint: '🪓🐉🔩✨🏆', wordHint: 'dagg' },
	{ itemName: 'Pet chaos elemental', emojiHint: '💥🐣✨❤️🏆', wordHint: 'pet' },
	{ itemName: 'Chaos elemental', emojiHint: '💥🌀😈✨🌑', wordHint: 'wilds' },
	{ itemName: 'Callisto cub', emojiHint: '🐻🐣✨❤️🏆', wordHint: 'pet' },
	{ itemName: 'Venenatis spiderling', emojiHint: '🕷️🐣✨❤️🏆', wordHint: 'pet' },
	{ itemName: "Vet'ion jr", emojiHint: '💀🐣✨❤️🏆', wordHint: 'pet' },

	// ============================================================
	// RAIDS DROPS (COX, TOB, TOA)
	// ============================================================
	{ itemName: 'Twisted bow', emojiHint: '🏹🌀✨💎🏆', wordHint: 'cox' },
	{ itemName: 'Scythe of vitur', emojiHint: '🌾💀🩸✨🏆', wordHint: 'tob' },
	{ itemName: 'Ghrazi rapier', emojiHint: '🗡️🔴⚔️✨🏆', wordHint: 'tob' },
	{ itemName: 'Sanguinesti staff', emojiHint: '🩸🪄🔮💀🏆', wordHint: 'tob' },
	{ itemName: 'Justiciar armour', emojiHint: '⚖️🛡️✨🏆🔵', wordHint: 'tob' },
	{ itemName: 'Avernic defender hilt', emojiHint: '🛡️⚔️🔴✨🏆', wordHint: 'tob' },
	{ itemName: "Lil' zik", emojiHint: '🦋🐣✨❤️🏆', wordHint: 'pet' },
	{ itemName: "Tumeken's shadow", emojiHint: '🌑🪄🔮🏛️🏆', wordHint: 'toa' },
	{ itemName: "Osmumten's fang", emojiHint: '🐍⚔️🏛️✨🏆', wordHint: 'toa' },
	{ itemName: "Elidinis' ward", emojiHint: '🏛️🛡️🔮✨🏆', wordHint: 'toa' },
	{ itemName: 'Masori armour', emojiHint: '🏛️🏹✨🛡️🏆', wordHint: 'toa' },
	{ itemName: 'Lightbearer', emojiHint: '💍💡✨🔦🏆', wordHint: 'toa' },
	{ itemName: 'Keris partisan of breaching', emojiHint: '🗡️💥🏛️✨🏆', wordHint: 'toa' },
	{ itemName: 'Thread of elidinis', emojiHint: '🧵🏛️✨🔮💎', wordHint: 'toa' },
	{ itemName: 'Olmlet', emojiHint: '🦎🐣✨❤️🏆', wordHint: 'pet' },
	{ itemName: 'Little nightmare', emojiHint: '😱🐣✨❤️🏆', wordHint: 'pet' },
	{ itemName: 'Nexling', emojiHint: '🏛️🐣✨❤️🏆', wordHint: 'pet' },

	// ============================================================
	// MISCELLANEOUS TRADEABLE
	// ============================================================
	{ itemName: 'Coins', emojiHint: '🪙💛💰🏦✨', wordHint: 'gold' },
	{ itemName: 'Noted item', emojiHint: '📄🪙💰✨🔄', wordHint: 'noted' },
	{ itemName: 'Crystal key', emojiHint: '💎🔑✨🏰🧝', wordHint: 'elf' },
	{ itemName: 'Dragonstone amulet', emojiHint: '📿🐉💎🔵✨', wordHint: 'glory' },
	{ itemName: 'Gout tuber', emojiHint: '🌿🌱🏝️✨🚜', wordHint: 'rare' },
	{ itemName: 'Magic stone', emojiHint: '🪨✨🏠🔮💎', wordHint: 'build' },
	{ itemName: 'Spirit shield', emojiHint: '🛡️👻✨🙏🔵', wordHint: 'spirit' },
	{ itemName: 'Holy elixir', emojiHint: '✝️💊✨🙏🟡', wordHint: 'holy' },
	{ itemName: 'Sigil', emojiHint: '💎👻✨🙏🔵', wordHint: 'sigil' },
	{ itemName: 'Armadyl sigil', emojiHint: '🦅💎✨🙏🔵', wordHint: 'sigil' },
	{ itemName: 'Spectral sigil', emojiHint: '👻💎✨🙏🔵', wordHint: 'sigil' },
	{ itemName: 'Arcane sigil', emojiHint: '🔮💎✨🙏🔵', wordHint: 'sigil' },
	{ itemName: 'Elysian sigil', emojiHint: '💙💎✨🙏🔵', wordHint: 'sigil' },
	{ itemName: 'Dragon platebody ornament kit', emojiHint: '🐉🛡️✨🎨📜', wordHint: 'clue' },
	{ itemName: 'Infernal max cape', emojiHint: '🌋🔥🏆✨👑', wordHint: 'max' },
	{ itemName: 'Tokhaar-kal', emojiHint: '🌋⚫🔥🏆🎭', wordHint: 'inferno' },
	{ itemName: 'Infernal max hood', emojiHint: '🌋🔥🏆✨⛑️', wordHint: 'max' },
	{ itemName: 'Chompy bird hat', emojiHint: '🐦🎩🏹✨😤', wordHint: 'hunt' },
	{ itemName: 'Kq head', emojiHint: '🐛👑💀✨🏆', wordHint: 'kq' },
	{ itemName: 'Kbd heads', emojiHint: '🐉👑💀✨🏆', wordHint: 'kbd' },
	{ itemName: 'Abyssal head', emojiHint: '🕳️👹💀✨🏆', wordHint: 'slayer' },
	{ itemName: 'Green dragon mask', emojiHint: '🐉🟢✨🎭🏆', wordHint: 'clue' },
	{ itemName: 'Blue dragon mask', emojiHint: '🐉🔵✨🎭🏆', wordHint: 'clue' },
	{ itemName: 'Red dragon mask', emojiHint: '🐉🔴✨🎭🏆', wordHint: 'clue' },
	{ itemName: 'Black dragon mask', emojiHint: '🐉⚫✨🎭🏆', wordHint: 'clue' },
	{ itemName: 'Jester hat', emojiHint: '🎭🃏✨😂🏆', wordHint: 'clue' },
	{ itemName: 'Gnome child hat', emojiHint: '🎭🌲✨👦🏆', wordHint: 'gnome' },
	{ itemName: 'Fedora', emojiHint: '🎩✨😎🏆📜', wordHint: 'clue' },
	{ itemName: 'Monocle', emojiHint: '🧐✨🏆📜🎭', wordHint: 'clue' },
	{ itemName: 'Musketeer hat', emojiHint: '🎩🗡️✨📜🏆', wordHint: 'clue' },
	{ itemName: 'Ham robes', emojiHint: '👘🥷🔴📜✨', wordHint: 'ham' },

	// ============================================================
	// NOTED TRADE GOODS & MISCELLANEOUS
	// ============================================================
	{ itemName: 'Tokkul', emojiHint: '🪙🌋⚫🔥🏪', wordHint: 'tzhaar' },
	{ itemName: 'Marks of grace', emojiHint: '🌟🏃✨🎭💨', wordHint: 'grace' },
	{ itemName: 'Slayer points', emojiHint: '💀⭐✨🔪🏆', wordHint: 'slay' },
	{ itemName: 'Agility ticket', emojiHint: '🤸🎟️✨🏃💨', wordHint: 'agile' },
	{ itemName: 'Castle wars ticket', emojiHint: '🏰⚔️🎟️✨🏆', wordHint: 'cwars' },
	{ itemName: 'Pest control points', emojiHint: '🐛⚔️⭐✨🏆', wordHint: 'pest' },
	{ itemName: 'Void seal', emojiHint: '⚪🏰⭐✨🏆', wordHint: 'void' },
	{ itemName: 'Twisted horns', emojiHint: '🌀🦌✨🎭🏆', wordHint: 'clue' },

	// ============================================================
	// SKILLING OUTFITS
	// ============================================================
	{ itemName: 'Lumberjack hat', emojiHint: '⛑️🌲🪓✨🟤', wordHint: 'wood' },
	{ itemName: 'Lumberjack top', emojiHint: '🛡️🌲🪓✨🟤', wordHint: 'wood' },
	{ itemName: 'Lumberjack legs', emojiHint: '👖🌲🪓✨🟤', wordHint: 'wood' },
	{ itemName: 'Lumberjack boots', emojiHint: '👢🌲🪓✨🟤', wordHint: 'wood' },
	{ itemName: 'Prospector helmet', emojiHint: '⛑️⛏️🪨✨🟡', wordHint: 'mining' },
	{ itemName: 'Prospector jacket', emojiHint: '🛡️⛏️🪨✨🟡', wordHint: 'mining' },
	{ itemName: 'Prospector legs', emojiHint: '👖⛏️🪨✨🟡', wordHint: 'mining' },
	{ itemName: 'Prospector boots', emojiHint: '👢⛏️🪨✨🟡', wordHint: 'mining' },
	{ itemName: 'Angler hat', emojiHint: '⛑️🎣🌊✨🔵', wordHint: 'fish' },
	{ itemName: 'Angler top', emojiHint: '🛡️🎣🌊✨🔵', wordHint: 'fish' },
	{ itemName: 'Angler waders', emojiHint: '👖🎣🌊✨🔵', wordHint: 'fish' },
	{ itemName: 'Angler boots', emojiHint: '👢🎣🌊✨🔵', wordHint: 'fish' },
	{ itemName: "Farmer's strawhat", emojiHint: '🎩🌾🌱✨🟡', wordHint: 'farm' },
	{ itemName: "Farmer's shirt", emojiHint: '🛡️🌾🌱✨🟡', wordHint: 'farm' },
	{ itemName: "Farmer's boro trousers", emojiHint: '👖🌾🌱✨🟡', wordHint: 'farm' },
	{ itemName: "Farmer's boots", emojiHint: '👢🌾🌱✨🟡', wordHint: 'farm' },
	{ itemName: 'Pyromancer hood', emojiHint: '⛑️🔥✨🌟🟠', wordHint: 'fire' },
	{ itemName: 'Pyromancer garb', emojiHint: '🛡️🔥✨🌟🟠', wordHint: 'fire' },
	{ itemName: 'Pyromancer robe', emojiHint: '👖🔥✨🌟🟠', wordHint: 'fire' },
	{ itemName: 'Pyromancer boots', emojiHint: '👢🔥✨🌟🟠', wordHint: 'fire' },
	{ itemName: "Rogues' top", emojiHint: '🛡️🥷✨🌟🖤', wordHint: 'thieve' },
	{ itemName: "Rogues' trousers", emojiHint: '👖🥷✨🌟🖤', wordHint: 'thieve' },
	{ itemName: "Rogues' gloves", emojiHint: '🤜🥷✨🌟🖤', wordHint: 'thieve' },
	{ itemName: "Rogues' boots", emojiHint: '👢🥷✨🌟🖤', wordHint: 'thieve' },
	{ itemName: "Rogues' mask", emojiHint: '🎭🥷✨🌟🖤', wordHint: 'thieve' },

	// ============================================================
	// PETS
	// ============================================================
	{ itemName: 'Heron', emojiHint: '🐦🎣✨❤️🏆', wordHint: 'pet' },
	{ itemName: 'Rock golem', emojiHint: '🪨🐉✨❤️🏆', wordHint: 'pet' },
	{ itemName: 'Beaver', emojiHint: '🦫🌲✨❤️🏆', wordHint: 'pet' },
	{ itemName: 'Giant squirrel', emojiHint: '🐿️🤸✨❤️🏆', wordHint: 'pet' },
	{ itemName: 'Tangleroot', emojiHint: '🌱🌳✨❤️🏆', wordHint: 'pet' },
	{ itemName: 'Rift guardian', emojiHint: '🕳️👾✨❤️🏆', wordHint: 'pet' },
	{ itemName: 'Baby chinchompa', emojiHint: '🐹💨✨❤️🏆', wordHint: 'pet' },
	{ itemName: 'Smolcano', emojiHint: '🌋🐣✨❤️🏆', wordHint: 'pet' },
	{ itemName: 'Bloodhound', emojiHint: '🐕🩸✨❤️🏆', wordHint: 'pet' },
	{ itemName: 'Phoenix', emojiHint: '🔥🐦✨❤️🏆', wordHint: 'pet' },
	{ itemName: 'Herbi', emojiHint: '🌿🐗✨❤️🏆', wordHint: 'pet' },
	{ itemName: 'Skotos', emojiHint: '🌑🐣✨❤️🏆', wordHint: 'pet' },
	{ itemName: 'Noon', emojiHint: '☀️🐣✨❤️🏆', wordHint: 'pet' },
	{ itemName: 'Midnight', emojiHint: '🌙🐣✨❤️🏆', wordHint: 'pet' },
	{ itemName: 'Strange old lockpick', emojiHint: '🔑👴✨🏆🔓', wordHint: 'clue' },

	// ============================================================
	// MINIGAME ITEMS
	// ============================================================
	{ itemName: 'Fighter hat', emojiHint: '⛑️⚔️💪✨🎮', wordHint: 'barb' },
	{ itemName: 'Fighter torso', emojiHint: '🛡️⚔️💪✨🎮', wordHint: 'barb' },
	{ itemName: 'Penance gloves', emojiHint: '🤜💪✨🎮🔵', wordHint: 'barb' },
	{ itemName: 'Pest control pack', emojiHint: '🐛⚔️⭐✨🎮', wordHint: 'pest' },
	{ itemName: 'Void mage helm', emojiHint: '⛑️🔮⚪✨🎮', wordHint: 'void' },
	{ itemName: 'Void ranger helm', emojiHint: '⛑️🏹⚪✨🎮', wordHint: 'void' },
	{ itemName: 'Void melee helm', emojiHint: '⛑️⚔️⚪✨🎮', wordHint: 'void' },
	{ itemName: 'Void knight top', emojiHint: '🛡️⚔️⚪✨🎮', wordHint: 'void' },
	{ itemName: 'Void knight robe', emojiHint: '👖⚔️⚪✨🎮', wordHint: 'void' },
	{ itemName: 'Elite void top', emojiHint: '🛡️⚔️⚪⭐🎮', wordHint: 'void' },
	{ itemName: 'Elite void robe', emojiHint: '👖⚔️⚪⭐🎮', wordHint: 'void' },
	{ itemName: 'Castlewars armour', emojiHint: '🏰🛡️⚔️✨🎮', wordHint: 'cwars' },
	{ itemName: 'Soul wars zeal', emojiHint: '👻⚔️⭐✨🎮', wordHint: 'soul' },

	// ============================================================
	// DIARIES & MISCELLANEOUS REWARDS
	// ============================================================
	{ itemName: 'Kandarin headband', emojiHint: '🎀🏙️✨🌟🏆', wordHint: 'diary' },
	{ itemName: 'Varrock armour', emojiHint: '🛡️🏰✨🌟🏆', wordHint: 'diary' },
	{ itemName: 'Falador shield', emojiHint: '🛡️🏰✨🌟🏆', wordHint: 'diary' },
	{ itemName: 'Morytania legs', emojiHint: '👖🌑✨🌟🏆', wordHint: 'diary' },
	{ itemName: 'Karamja gloves', emojiHint: '🤜🏝️✨🌟🏆', wordHint: 'diary' },
	{ itemName: 'Desert amulet', emojiHint: '📿🏜️✨🌟🏆', wordHint: 'diary' },
	{ itemName: 'Fremennik sea boots', emojiHint: '👢🌊✨🌟🏆', wordHint: 'diary' },
	{ itemName: 'Lumbridge ring', emojiHint: '💍🏰✨🌟🏆', wordHint: 'diary' },
	{ itemName: 'Western banner', emojiHint: '🏳️🌍✨🌟🏆', wordHint: 'diary' },
	{ itemName: 'Wilderness sword', emojiHint: '⚔️🌑✨🌟🏆', wordHint: 'diary' },

	// ============================================================
	// DYES & COSMETICS
	// ============================================================
	{ itemName: 'Red dye', emojiHint: '🔴🎨✨🌿🔧', wordHint: 'color' },
	{ itemName: 'Yellow dye', emojiHint: '🟡🎨✨🌿🔧', wordHint: 'color' },
	{ itemName: 'Blue dye', emojiHint: '🔵🎨✨🌿🔧', wordHint: 'color' },
	{ itemName: 'Orange dye', emojiHint: '🟠🎨✨🌿🔧', wordHint: 'color' },
	{ itemName: 'Green dye', emojiHint: '🟢🎨✨🌿🔧', wordHint: 'color' },
	{ itemName: 'Purple dye', emojiHint: '🟣🎨✨🌿🔧', wordHint: 'color' },
	{ itemName: 'Pink dye', emojiHint: '🩷🎨✨🌿🔧', wordHint: 'color' },
	{ itemName: 'Black dye', emojiHint: '⚫🎨✨🌿🔧', wordHint: 'color' },
	{ itemName: 'Gnome scarf', emojiHint: '🧣🌲✨🎭🟢', wordHint: 'gnome' },
	{ itemName: 'Bunny ears', emojiHint: '🐰👂✨🎭🏆', wordHint: 'event' },
	{ itemName: 'Rubber chicken', emojiHint: '🐔🦠✨🎭🏆', wordHint: 'event' },
	{ itemName: 'Scythe', emojiHint: '🌾⚔️✨🎭🏆', wordHint: 'event' },
	{ itemName: 'Easter egg', emojiHint: '🥚🐣✨🎭🏆', wordHint: 'event' },
	{ itemName: 'Christmas cracker', emojiHint: '🎉🎁✨🎭🏆', wordHint: 'event' },
	{ itemName: 'Santa hat', emojiHint: '🎅🎩✨🎭🏆', wordHint: 'event' },
	{ itemName: 'Partyhat', emojiHint: '🎉🎩✨🎭🏆', wordHint: 'event' },
	{ itemName: 'Yo-yo', emojiHint: '🪀✨🎭🏆🎁', wordHint: 'event' },

	// ============================================================
	// CONSTRUCTION ITEMS
	// ============================================================
	{ itemName: 'Plank', emojiHint: '🪵🏠🔧🌲✨', wordHint: 'build' },
	{ itemName: 'Oak plank', emojiHint: '🪵🌳🏠🔧✨', wordHint: 'build' },
	{ itemName: 'Teak plank', emojiHint: '🪵🌴🏠🔧✨', wordHint: 'build' },
	{ itemName: 'Mahogany plank', emojiHint: '🪵🌴🏛️🔧✨', wordHint: 'build' },
	{ itemName: 'Marble block', emojiHint: '🪨⚪🏛️🔧✨', wordHint: 'build' },
	{ itemName: 'Magic stone', emojiHint: '🪨🔮🏛️🔧✨', wordHint: 'build' },
	{ itemName: 'Gold leaf', emojiHint: '🍃🟡🏛️🔧✨', wordHint: 'build' },
	{ itemName: 'Bolt of cloth', emojiHint: '🧵🏠🔧✨🏛️', wordHint: 'build' },
	{ itemName: 'Steel bar (construction)', emojiHint: '⚙️🔩🏠🔧✨', wordHint: 'build' },
	{ itemName: 'Battleaxe', emojiHint: '🪓⚔️💪🏠🔧', wordHint: 'build' },
	{ itemName: 'Clockwork', emojiHint: '⏰⚙️🔧🏠✨', wordHint: 'build' },
	{ itemName: 'Toy soldier', emojiHint: '🪆⚙️🔧🏠✨', wordHint: 'build' },
	{ itemName: 'Toy doll', emojiHint: '🪆🏠🔧✨🎁', wordHint: 'build' },
	{ itemName: 'Toy cat', emojiHint: '🐱🏠🔧✨🎁', wordHint: 'build' },
	{ itemName: 'Toy mouse', emojiHint: '🐭🏠🔧✨🎁', wordHint: 'build' },

	// ============================================================
	// COOKING INGREDIENTS
	// ============================================================
	{ itemName: 'Potato', emojiHint: '🥔🌱🍽️🌾🚜', wordHint: 'cook' },
	{ itemName: 'Onion', emojiHint: '🧅😢🌱🍽️🌾', wordHint: 'cook' },
	{ itemName: 'Cabbage', emojiHint: '🥬🟢🌱🍽️🌾', wordHint: 'cook' },
	{ itemName: 'Tomato', emojiHint: '🍅🔴🌱🍽️🌾', wordHint: 'cook' },
	{ itemName: 'Banana', emojiHint: '🍌🌴🐒🍽️🌾', wordHint: 'cook' },
	{ itemName: 'Lemon', emojiHint: '🍋🟡🌱🍽️🌾', wordHint: 'cook' },
	{ itemName: 'Orange', emojiHint: '🍊🟠🌱🍽️🌾', wordHint: 'cook' },
	{ itemName: 'Pineapple chunk', emojiHint: '🍍🏝️🌱🍽️🌾', wordHint: 'cook' },
	{ itemName: 'Cheese', emojiHint: '🧀🐄🥛🍽️🌾', wordHint: 'cook' },
	{ itemName: 'Egg', emojiHint: '🥚🐔🍳🍽️🌾', wordHint: 'cook' },
	{ itemName: 'Flour', emojiHint: '🌾⚙️🍞🍽️🌾', wordHint: 'cook' },
	{ itemName: 'Pot of flour', emojiHint: '🪣🌾🍞🍽️🌾', wordHint: 'cook' },
	{ itemName: 'Bucket of milk', emojiHint: '🪣🥛🐄🍽️🌾', wordHint: 'cook' },
	{ itemName: 'Chocolate dust', emojiHint: '🍫💨🎂🍽️🌾', wordHint: 'cook' },
	{ itemName: 'Chocolate bar', emojiHint: '🍫🎂🍽️🌾🟤', wordHint: 'cook' },
	{ itemName: 'Bucket of water', emojiHint: '🪣💧🌊🍽️🌾', wordHint: 'cook' },
	{ itemName: 'Pie shell', emojiHint: '🥧🌾🍽️🔧✨', wordHint: 'cook' },
	{ itemName: 'Uncooked pizza', emojiHint: '🍕🌾🍅🍽️🔧', wordHint: 'cook' },
	{ itemName: 'Uncooked cake', emojiHint: '🎂🌾🥚🍽️🔧', wordHint: 'cook' },
	{ itemName: 'Raw beef', emojiHint: '🥩🐄🌾🍽️🔴', wordHint: 'cook' },
	{ itemName: 'Raw chicken', emojiHint: '🐔🌾🍽️🔴🥩', wordHint: 'cook' },
	{ itemName: 'Raw rabbit', emojiHint: '🐇🌾🍽️🔴🥩', wordHint: 'cook' },

	// ============================================================
	// LEATHER & CRAFTING MATERIALS
	// ============================================================
	{ itemName: 'Leather', emojiHint: '🐄✂️🧵💍🔧', wordHint: 'craft' },
	{ itemName: 'Hard leather', emojiHint: '🐄✂️🧵💪🔧', wordHint: 'craft' },
	{ itemName: 'Snakeskin', emojiHint: '🐍✂️🧵🎯🔧', wordHint: 'craft' },
	{ itemName: 'Green dragonhide', emojiHint: '🐉🟢✂️🧵🔧', wordHint: 'craft' },
	{ itemName: 'Blue dragonhide', emojiHint: '🐉🔵✂️🧵🔧', wordHint: 'craft' },
	{ itemName: 'Red dragonhide', emojiHint: '🐉🔴✂️🧵🔧', wordHint: 'craft' },
	{ itemName: 'Black dragonhide', emojiHint: '🐉⚫✂️🧵🔧', wordHint: 'craft' },
	{ itemName: 'Royal dragonhide', emojiHint: '🐉👑✂️🧵🔧', wordHint: 'craft' },
	{ itemName: "Green d'hide body", emojiHint: '🐉🟢🛡️🎯🔧', wordHint: 'range' },
	{ itemName: "Blue d'hide body", emojiHint: '🐉🔵🛡️🎯🔧', wordHint: 'range' },
	{ itemName: "Red d'hide body", emojiHint: '🐉🔴🛡️🎯🔧', wordHint: 'range' },
	{ itemName: "Black d'hide body", emojiHint: '🐉⚫🛡️🎯🔧', wordHint: 'range' },
	{ itemName: 'Coif', emojiHint: '⛑️🌿🧵🎯🔧', wordHint: 'range' },
	{ itemName: 'Leather cowl', emojiHint: '⛑️🐄🧵🎯🔧', wordHint: 'range' },
	{ itemName: 'Studded body', emojiHint: '🛡️🔩🐄🎯🔧', wordHint: 'range' },
	{ itemName: 'Studded chaps', emojiHint: '👖🔩🐄🎯🔧', wordHint: 'range' },
	{ itemName: 'Hardleather body', emojiHint: '🛡️🐄💪🎯🔧', wordHint: 'range' },
	{ itemName: 'Blessed coif', emojiHint: '⛑️✝️🧵🎯🔧', wordHint: 'range' },
	{ itemName: 'Blessed body', emojiHint: '🛡️✝️🧵🎯🔧', wordHint: 'range' },
	{ itemName: 'Blessed chaps', emojiHint: '👖✝️🧵🎯🔧', wordHint: 'range' },
	{ itemName: 'Blessed bracers', emojiHint: '🤜✝️🧵🎯🔧', wordHint: 'range' },
	{ itemName: 'Blessed boots', emojiHint: '👢✝️🧵🎯🔧', wordHint: 'range' },
	{ itemName: "Karil's crossbow", emojiHint: '⚰️🔩🏹🎯🔧', wordHint: 'barrows' },

	// ============================================================
	// MYSTIC & MAGIC ARMOUR
	// ============================================================
	{ itemName: 'Mystic hat', emojiHint: '🎩🔮✨🟣🌀', wordHint: 'mystic' },
	{ itemName: 'Mystic robe top', emojiHint: '🛡️🔮✨🟣🌀', wordHint: 'mystic' },
	{ itemName: 'Mystic robe bottom', emojiHint: '👖🔮✨🟣🌀', wordHint: 'mystic' },
	{ itemName: 'Mystic gloves', emojiHint: '🤜🔮✨🟣🌀', wordHint: 'mystic' },
	{ itemName: 'Mystic boots', emojiHint: '👢🔮✨🟣🌀', wordHint: 'mystic' },
	{ itemName: 'Splitbark helm', emojiHint: '⛑️🌲🔮✨🟣', wordHint: 'magic' },
	{ itemName: 'Splitbark body', emojiHint: '🛡️🌲🔮✨🟣', wordHint: 'magic' },
	{ itemName: 'Splitbark legs', emojiHint: '👖🌲🔮✨🟣', wordHint: 'magic' },
	{ itemName: 'Splitbark gauntlets', emojiHint: '🤜🌲🔮✨🟣', wordHint: 'magic' },
	{ itemName: 'Splitbark boots', emojiHint: '👢🌲🔮✨🟣', wordHint: 'magic' },
	{ itemName: 'Infinity hat', emojiHint: '🎩♾️🔮✨🟣', wordHint: 'mta' },
	{ itemName: 'Infinity top', emojiHint: '🛡️♾️🔮✨🟣', wordHint: 'mta' },
	{ itemName: 'Infinity bottoms', emojiHint: '👖♾️🔮✨🟣', wordHint: 'mta' },
	{ itemName: 'Infinity gloves', emojiHint: '🤜♾️🔮✨🟣', wordHint: 'mta' },
	{ itemName: 'Infinity boots', emojiHint: '👢♾️🔮✨🟣', wordHint: 'mta' },
	{ itemName: "Dagon'hai hat", emojiHint: '⛑️😈🔮✨🟣', wordHint: 'magic' },
	{ itemName: "Dagon'hai robe top", emojiHint: '🛡️😈🔮✨🟣', wordHint: 'magic' },
	{ itemName: "Dagon'hai robe bottom", emojiHint: '👖😈🔮✨🟣', wordHint: 'magic' },

	// ============================================================
	// MISCELLANEOUS USEFUL ITEMS
	// ============================================================
	{ itemName: 'Camulet', emojiHint: '📿🐪🏜️✨⚡', wordHint: 'camel' },
	{ itemName: 'Ring of charos', emojiHint: '💍😇✨🗣️🔵', wordHint: 'charm' },
	{ itemName: 'Skull sceptre', emojiHint: '💀🪄✨⚡🌑', wordHint: 'wilds' },
	{ itemName: 'Burning amulet', emojiHint: '📿🔥✨⚡🌑', wordHint: 'wilds' },
	{ itemName: 'Crumble undead', emojiHint: '🧟💥🔮✨⚔️', wordHint: 'spell' },
	{ itemName: 'Humidify', emojiHint: '💧💨🔮✨⚗️', wordHint: 'spell' },
	{ itemName: 'String jewellery', emojiHint: '💍🧵🔮✨⚗️', wordHint: 'spell' },
	{ itemName: 'Tan leather', emojiHint: '🐄🧵🔮✨⚗️', wordHint: 'spell' },
	{ itemName: 'Plank make', emojiHint: '🪵🏠🔮✨⚗️', wordHint: 'spell' },
	{ itemName: 'Superheat item', emojiHint: '🔥⚒️🔮✨⚗️', wordHint: 'spell' },
	{ itemName: 'High alchemy', emojiHint: '🔥🪙🔮✨⚗️', wordHint: 'alch' },
	{ itemName: 'Low alchemy', emojiHint: '🪙🔮✨⚗️🌿', wordHint: 'alch' },
	{ itemName: 'Enchant ruby', emojiHint: '💎🔴🔮✨⚗️', wordHint: 'ench' },
	{ itemName: 'Charge orb', emojiHint: '⚡🔮✨⭕⚗️', wordHint: 'spell' },
	{ itemName: 'Ensouled goblin head', emojiHint: '👺💀🔮✨🙏', wordHint: 'pray' },
	{ itemName: 'Ensouled dragon head', emojiHint: '🐉💀🔮✨🙏', wordHint: 'pray' },
	{ itemName: 'Rune pouch', emojiHint: '👜🔮✨⭕💊', wordHint: 'store' },
	{ itemName: 'Herb sack', emojiHint: '🎒🌿✨💊🌾', wordHint: 'store' },
	{ itemName: 'Gem bag', emojiHint: '👜💎✨⭕💊', wordHint: 'store' },
	{ itemName: 'Looting bag', emojiHint: '👜🌑✨⭕💊', wordHint: 'wilds' },
	{ itemName: 'Coal bag', emojiHint: '👜⚫✨⭕💊', wordHint: 'store' },
	{ itemName: 'Seed box', emojiHint: '📦🌱✨⭕💊', wordHint: 'store' },
	{ itemName: 'Log basket', emojiHint: '🧺🌲✨⭕💊', wordHint: 'store' },
	{ itemName: 'Fish barrel', emojiHint: '🐟🛢️✨⭕💊', wordHint: 'store' },
	{ itemName: 'Ore box', emojiHint: '📦⛏️✨⭕💊', wordHint: 'store' },
	{ itemName: 'Fossil island note', emojiHint: '🦴📜✨🏝️💎', wordHint: 'fossil' },
	{ itemName: 'Unidentified small fossil', emojiHint: '🦴🏝️✨❓🔍', wordHint: 'fossil' },
	{ itemName: 'Unidentified medium fossil', emojiHint: '🦕🏝️✨❓🔍', wordHint: 'fossil' },
	{ itemName: 'Unidentified large fossil', emojiHint: '🦖🏝️✨❓🔍', wordHint: 'fossil' },
	{ itemName: 'Unidentified rare fossil', emojiHint: '💎🏝️✨❓🔍', wordHint: 'fossil' },
	{ itemName: 'Numulite', emojiHint: '🪙🏝️🦕✨🔧', wordHint: 'fossil' },
	{ itemName: "Mermaid's tear", emojiHint: '🧜💧✨🏝️💎', wordHint: 'seaweed' },
	{ itemName: 'Seaweed', emojiHint: '🌿🌊💚🏝️🔧', wordHint: 'seaweed' },
	{ itemName: 'Giant seaweed', emojiHint: '🌿🌊💚🏝️💎', wordHint: 'seaweed' },
	{ itemName: 'White lily', emojiHint: '🌸⚪🌱🌿🚜', wordHint: 'farm' },
	{ itemName: 'Marigold', emojiHint: '🌼🌱🌾🌿🚜', wordHint: 'allot' },
	{ itemName: 'Jangerberries', emojiHint: '🫐🌿🧪🌾✨', wordHint: 'herby' },
	{ itemName: 'White berries', emojiHint: '⚪🫐🌿🧪✨', wordHint: 'herby' },
	{ itemName: 'Potato cactus', emojiHint: '🌵🥔✨🌿🧪', wordHint: 'herby' },
	{ itemName: 'Mort myre fungus', emojiHint: '🍄🌑✨🌿🧪', wordHint: 'herby' },
	{ itemName: 'Crushed nest', emojiHint: '🐦🪹✨🌿🧪', wordHint: 'herby' },
	{ itemName: 'Dragon scale dust', emojiHint: '🐉💨✨🌿🧪', wordHint: 'herby' },
	{ itemName: 'Wine of zamorak', emojiHint: '🍷😈✨🌿🧪', wordHint: 'herby' },
	{ itemName: 'Unicorn horn dust', emojiHint: '🦄🌿✨🧪💊', wordHint: 'herby' },
	{ itemName: 'Blue dragon scale', emojiHint: '🐉🔵✨🌿🧪', wordHint: 'herby' },
	{ itemName: "Red spiders' eggs", emojiHint: '🕷️🔴🥚✨🧪', wordHint: 'herby' },
	{ itemName: 'Toads legs', emojiHint: '🐸🦵✨🌿🧪', wordHint: 'herby' },
	{ itemName: 'Limpwurt root', emojiHint: '🔴🌱🌿🧪✨', wordHint: 'herby' },
	{ itemName: 'Snape grass', emojiHint: '🌿🌱🌾🧪✨', wordHint: 'herby' },
	{ itemName: 'Eye of newt', emojiHint: '👁️🐸🌿🧪✨', wordHint: 'herby' },
	{ itemName: 'Ashes', emojiHint: '🔥⚫💨🙏🧪', wordHint: 'herby' },
	{ itemName: 'Nail beast nails', emojiHint: '🔩🐛✨🌿🧪', wordHint: 'herby' },
	{ itemName: 'Swamp tar', emojiHint: '⚫🌿💧🧪✨', wordHint: 'herby' },
	{ itemName: 'Coconut milk', emojiHint: '🥥💧🌿🧪✨', wordHint: 'herby' },
	{ itemName: 'Coconut', emojiHint: '🥥🌴🌿🌾🔧', wordHint: 'cook' },
	{ itemName: 'Kebab', emojiHint: '🍢🔥🍽️🌶️🌾', wordHint: 'eat' },
	{ itemName: 'Eel sushi', emojiHint: '🍣🐍🌊🍽️✨', wordHint: 'eat' },
	{ itemName: 'Dragonfruit', emojiHint: '🍈🐉🌱🌿🌴', wordHint: 'fruit' },
	{ itemName: 'Papaya fruit', emojiHint: '🍈🌴🌿🌱🍽️', wordHint: 'fruit' },
	{ itemName: 'Pineapple', emojiHint: '🍍🌴🌿🌱🍽️', wordHint: 'fruit' },
	{ itemName: 'Watermelon', emojiHint: '🍉🌿🌱🌾🍽️', wordHint: 'fruit' },
	{ itemName: 'Golovanova fruit top', emojiHint: '🍊🍈🌿🌱🍽️', wordHint: 'fruit' },
	{ itemName: 'Celastrus bark', emojiHint: '🌲🌿🏹✨🔧', wordHint: 'fletch' },
	{ itemName: 'Battlestaff', emojiHint: '🪄⚔️🔮⭕🌀', wordHint: 'magic' },
	{ itemName: 'Orb of water', emojiHint: '⭕💧🔮✨🌀', wordHint: 'orb' },
	{ itemName: 'Orb of fire', emojiHint: '⭕🔥🔮✨🌀', wordHint: 'orb' },
	{ itemName: 'Orb of air', emojiHint: '⭕💨🔮✨🌀', wordHint: 'orb' },
	{ itemName: 'Orb of earth', emojiHint: '⭕🌍🔮✨🌀', wordHint: 'orb' },
	{ itemName: 'Mahogany homes', emojiHint: '🏠🌴🪵🔧✨', wordHint: 'build' },
	{ itemName: 'Supply crate', emojiHint: '📦🌊🎣🔧✨', wordHint: 'trawl' }
];
