name: Daily Notifications

on:
  workflow_run:
    workflows: ['Deploy OSRS Guessing Game']
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Send Success Message
        run: |
          curl -H "Content-Type: application/json" \
               -d '{
                 "username": "Scapedle Announcer",
                 "content": "🗓️ **A new daily Scapedle is live!** \nCheck it out here: https://scapedle.com"
               }' \
               ${{ secrets.DAILY_WEBHOOK }}
